# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class BtEnvMqtt < Formula
  desc "Macos tool that publishes details about nearby bluetooth devices to mqtt"
  homepage "https://github.com/cdzombak/bt-env-mqtt"
  url "https://github.com/cdzombak/bt-env-mqtt/archive/refs/tags/v0.0.2.tar.gz"
  version "0.0.2"
  sha256 "474d718eee2aa6584e60a19615f0ddcae1caddd3912780ad9427a05b0685fc23"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/bt-env-mqtt/releases/download/v0.0.2/bt-env-mqtt-0.0.2-darwin-amd64.tar.gz"
      sha256 "768541a4b2a44749474a7fb16f7dbac9d7d897cb2d21c6044ea533d664e1363f"
    end

    on_arm do
      url "https://github.com/cdzombak/bt-env-mqtt/releases/download/v0.0.2/bt-env-mqtt-0.0.2-darwin-arm64.tar.gz"
      sha256 "002a2876d2ea56a86299c4130d21eb5d7847b6ca9595ae7ceacc1ccf828daeef"
    end
  end

  def install
    bin.install "bt-env-mqtt"
  end

  test do
    assert_match("0.0.2", shell_output("#{bin}/bt-env-mqtt -version"))
  end
end
