# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Dirshard < Formula
  desc "Produce sharded path fragments from a filename"
  homepage "https://github.com/cdzombak/dirshard"
  url "https://github.com/cdzombak/dirshard/archive/v1.1.3.tar.gz"
  sha256 "81bdc5b9b795cfa20c55c3dc8ae778653727ad3a83caf97323fabc052ab27f89"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "dirshard"
  end

  test do
    assert_match("1.1.3", shell_output("dirshard -version"))
  end
end
