# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Dirshard < Formula
  desc "Produce sharded path fragments from a filename"
  homepage "https://github.com/cdzombak/dirshard"
  url "https://github.com/cdzombak/dirshard/archive/v1.1.4.tar.gz"
  sha256 "0bea52e25f997c73a7fd75494843499247e35b21e200c2f8335cb05e2308093e"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "dirshard"
  end

  test do
    assert_match("1.1.4", shell_output("dirshard -version"))
  end
end
