# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Dirshard < Formula
  desc "Produce sharded path fragments from a filename"
  homepage "https://github.com/cdzombak/dirshard"
  url "https://github.com/cdzombak/dirshard/archive/refs/tags/v1.2.4.tar.gz"
  sha256 "e3bff21c468875e152adad952b4ea77f302ed249094d6d405c3d57a41db7f753"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/dirshard/releases/download/v1.2.4/dirshard-1.2.4-darwin-amd64.tar.gz"
      sha256 "80607bbff664858c86b9579b0ab71ac56638b7b502beed3e7bce7b5bc75d7cae"
    end

    on_arm do
      url "https://github.com/cdzombak/dirshard/releases/download/v1.2.4/dirshard-1.2.4-darwin-arm64.tar.gz"
      sha256 "40b1e24ace6a46a373541c79bf4985eed4cc174718dd9e72fc12c38c0b86fa63"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/dirshard/releases/download/v1.2.4/dirshard-1.2.4-linux-amd64.tar.gz"
      sha256 "ca772cf6147aa6c1e2d64828acb8657bba7410af0398adf6d53c4cc21c9fa4c9"
    end

    on_arm do
      url "https://github.com/cdzombak/dirshard/releases/download/v1.2.4/dirshard-1.2.4-linux-arm64.tar.gz"
      sha256 "42bea2c0cb9342986b9f916954385957be08a38701897163e139e24720ee1325"
    end
  end

  def install
    bin.install "dirshard"
  end

  test do
    assert_match("1.2.4", shell_output("#{bin}/dirshard -version"))
  end
end
