# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class EbirdRss < Formula
  desc "Generate an rss, atom, or json feed of your most recent bird sightings from an e"
  homepage "https://github.com/cdzombak/ebird-rss"
  url "https://github.com/cdzombak/ebird-rss/archive/refs/tags/v0.0.2.tar.gz"
  version "0.0.2"
  sha256 "7a172f90a34de9ae47d94684690a78353d09848f29777c2da55dd26e92c3d435"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/ebird-rss/releases/download/v0.0.2/ebird-rss-0.0.2-darwin-amd64.tar.gz"
      sha256 "ba6b14b55b1dbebe64161d37289236c73ef4845f0978ae16aadcaab97acef53f"
    end

    on_arm do
      url "https://github.com/cdzombak/ebird-rss/releases/download/v0.0.2/ebird-rss-0.0.2-darwin-arm64.tar.gz"
      sha256 "c9394815ea53e298e5db2ac13b4503f215c77655f1e72328e709850f8dba1ddc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/ebird-rss/releases/download/v0.0.2/ebird-rss-0.0.2-linux-amd64.tar.gz"
      sha256 "5caeb4e02dfcb6defdd6a83f260c172c2373a44f23c44334dc4dd2ae2c2bf78f"
    end

    on_arm do
      url "https://github.com/cdzombak/ebird-rss/releases/download/v0.0.2/ebird-rss-0.0.2-linux-arm64.tar.gz"
      sha256 "d28cbc71935ee05948cb39172e4340280bcc2b90e0b539ceb473a5bffa023509"
    end
  end

  def install
    bin.install "ebird-rss"
  end

  test do
    assert_match("0.0.2", shell_output("#{bin}/ebird-rss -version"))
  end
end
