# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class EbirdRss < Formula
  desc "Generate an rss, atom, or json feed of your most recent bird sightings from an e"
  homepage "https://github.com/cdzombak/ebird-rss"
  url "https://github.com/cdzombak/ebird-rss/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "965c42258585cc4480b9114ffd7df44ded41650f1f3346c7c6f1b571838361a7"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/ebird-rss/releases/download/v0.0.1/ebird-rss-0.0.1-darwin-amd64.tar.gz"
      sha256 "7e34ad448e428c84ce31dd7d22c5794759ffe2108f4b6dbc47aff72b7700a662"
    end

    on_arm do
      url "https://github.com/cdzombak/ebird-rss/releases/download/v0.0.1/ebird-rss-0.0.1-darwin-arm64.tar.gz"
      sha256 "6e1e3a1bc939b38eeb5ca09856b0566559e0c02425782980e52ee7ad84b1607d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/ebird-rss/releases/download/v0.0.1/ebird-rss-0.0.1-linux-amd64.tar.gz"
      sha256 "3e228b319638c504e24d704cfed6db42f98441974149ac908ee2b4e546da549b"
    end

    on_arm do
      url "https://github.com/cdzombak/ebird-rss/releases/download/v0.0.1/ebird-rss-0.0.1-linux-arm64.tar.gz"
      sha256 "ed133ec8f1ed77ca0b54401ea56a6cfd5eefa2a6077099a8f12be47171924a31"
    end
  end

  def install
    bin.install "ebird-rss"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/ebird-rss -version"))
  end
end
