# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class EnergybridgeToInfluxdb < Formula
  desc "Pull electricity usage readings from an energy bridge via mqtt and ship them to"
  homepage "https://github.com/cdzombak/energybridge_to_influxdb"
  url "https://github.com/cdzombak/energybridge_to_influxdb/archive/refs/tags/v1.0.1.tar.gz"
  sha256 "9199978714365f1c63d2424d0da0f3b434baf22174629e44437d726862c2393b"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/energybridge_to_influxdb/releases/download/v1.0.1/energybridge_to_influxdb-1.0.1-darwin-amd64.tar.gz"
      sha256 "82699956e397d8c7ac1d1466f702fbeda6fd94aba1206314e9d1c9300d2eeae4"
    end

    on_arm do
      url "https://github.com/cdzombak/energybridge_to_influxdb/releases/download/v1.0.1/energybridge_to_influxdb-1.0.1-darwin-arm64.tar.gz"
      sha256 "b6e5ea9875f14bb9909ad5deaa4297054d0e1c011fd11d0988b4a0f58e8245be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/energybridge_to_influxdb/releases/download/v1.0.1/energybridge_to_influxdb-1.0.1-linux-amd64.tar.gz"
      sha256 "ced64e0c580fa5c96c8ced1e4a0e5098a28c4eecaed738b77561b86f4392cdf9"
    end

    on_arm do
      url "https://github.com/cdzombak/energybridge_to_influxdb/releases/download/v1.0.1/energybridge_to_influxdb-1.0.1-linux-arm64.tar.gz"
      sha256 "6a0d224cb13de5f682bcad440c917f39c5947136758e4a5d4e55d2530cd811ed"
    end
  end

  def install
    bin.install "energybridge_to_influxdb"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/energybridge_to_influxdb -version"))
  end
end
