# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class EnergybridgeToInfluxdb < Formula
  desc "Pull electricity usage readings from an energy bridge via mqtt and ship them to"
  homepage "https://github.com/cdzombak/energybridge_to_influxdb"
  url "https://github.com/cdzombak/energybridge_to_influxdb/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "c36e51caae0eded073709b8a5b4b7146a9230f1bbfec3bb7087ac2c284c023a6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/energybridge_to_influxdb/releases/download/v1.0.0/energybridge_to_influxdb-1.0.0-darwin-amd64.tar.gz"
      sha256 "07e795ae9e58ac51206e719edb3a24d491785992ea566b8e6de8dba2226fbb10"
    end

    on_arm do
      url "https://github.com/cdzombak/energybridge_to_influxdb/releases/download/v1.0.0/energybridge_to_influxdb-1.0.0-darwin-arm64.tar.gz"
      sha256 "e6652785b1721155a4490a140d3efcefc1cc539fbc428adf8ccc6483998244fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/energybridge_to_influxdb/releases/download/v1.0.0/energybridge_to_influxdb-1.0.0-linux-amd64.tar.gz"
      sha256 "c599a5b336d91328b5f28092b305bb32620dd56abd378377013a1bab07b8db44"
    end

    on_arm do
      url "https://github.com/cdzombak/energybridge_to_influxdb/releases/download/v1.0.0/energybridge_to_influxdb-1.0.0-linux-arm64.tar.gz"
      sha256 "c53fbf21ae8d0c42eb7ee2129049e32226a32cb1ee03d748f5f95961e7123267"
    end
  end

  def install
    bin.install "energybridge_to_influxdb"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/energybridge_to_influxdb -version"))
  end
end
