# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Eztag < Formula
  desc "Quickly & easily create tags in your github repositories"
  homepage "https://github.com/cdzombak/eztag"
  url "https://github.com/cdzombak/eztag/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "802c25c2859710001c62da3970a67ece7eb66e27c637626c8ef2913ff0b3e8aa"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/eztag/releases/download/v1.0.0/eztag-1.0.0-darwin-amd64.tar.gz"
      sha256 "a7d0cf6bef21858c053fd9daceb62a24bc4127dc8f260c1f804ea2d50d62f32a"
    end

    on_arm do
      url "https://github.com/cdzombak/eztag/releases/download/v1.0.0/eztag-1.0.0-darwin-arm64.tar.gz"
      sha256 "a8ff3e466ec29805989a88d9634f53b1711d3645b50b074ef79b2f04a38aa6ac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/eztag/releases/download/v1.0.0/eztag-1.0.0-linux-amd64.tar.gz"
      sha256 "42a989662e84539202150456bffbcf74af36f601de446f3a27a77bcae05b14cf"
    end

    on_arm do
      url "https://github.com/cdzombak/eztag/releases/download/v1.0.0/eztag-1.0.0-linux-arm64.tar.gz"
      sha256 "56cab2182ecc9ade2ded65e691d70675f0c263502ebf679a7707c2fadac9d207"
    end
  end

  def install
    bin.install "eztag"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/eztag -version"))
  end
end
