# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Eztag < Formula
  desc "Quickly &amp; easily create tags in your github repositories"
  homepage "https://github.com/cdzombak/eztag"
  url "https://github.com/cdzombak/eztag/archive/refs/tags/v0.0.3.tar.gz"
  version "0.0.3"
  sha256 "9bbf83553071a29057721b0005a8fa9b8f0bf849b16edbef3b4501dbcd1defa8"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/eztag/releases/download/v0.0.3/eztag-0.0.3-darwin-amd64.tar.gz"
      sha256 "075b05d5c3361719587bf020ec82890fb32ab87f303034497e9d71639e13cb29"
    end

    on_arm do
      url "https://github.com/cdzombak/eztag/releases/download/v0.0.3/eztag-0.0.3-darwin-arm64.tar.gz"
      sha256 "d0e8355fcc267cdd22eda64c5c94b903a0c103d9dcd855be6b3fe929eb834285"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/eztag/releases/download/v0.0.3/eztag-0.0.3-linux-amd64.tar.gz"
      sha256 "ee602195b5ac0ab3cae68bb79c3ce171096a97ff74f87073c9cbd9cedbcd7d6d"
    end

    on_arm do
      url "https://github.com/cdzombak/eztag/releases/download/v0.0.3/eztag-0.0.3-linux-arm64.tar.gz"
      sha256 "96e4ae7fec5978d569d479f5ff9d5749b9fb9be2260e57a9ff55e0dabb725ac6"
    end
  end

  def install
    bin.install "eztag"
  end

  test do
    assert_match("0.0.3", shell_output("#{bin}/eztag -version"))
  end
end
