# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Eztag < Formula
  desc "Quickly &amp; easily create tags in your github repositories"
  homepage "https://github.com/cdzombak/eztag"
  url "https://github.com/cdzombak/eztag/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "2373ecf3a5d84eda7f8c3d9bae235f0b1ced7031776eadc2955f052eb2a19440"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/eztag/releases/download/v0.0.1/eztag-0.0.1-darwin-amd64.tar.gz"
      sha256 "e3bfa8c0ea2e2e81ee85318209c8e487efd7efa575f6364f4e2fffabb6951f45"
    end

    on_arm do
      url "https://github.com/cdzombak/eztag/releases/download/v0.0.1/eztag-0.0.1-darwin-arm64.tar.gz"
      sha256 "c652dcecc2f2fd673d49551673e3a5afa40ceaf8a45e1fbc2defa95590662e6d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/eztag/releases/download/v0.0.1/eztag-0.0.1-linux-amd64.tar.gz"
      sha256 "3494bbece369f4f9595511088f503e4569ec1c0757cfe4fdd55cc37fa549dda5"
    end

    on_arm do
      url "https://github.com/cdzombak/eztag/releases/download/v0.0.1/eztag-0.0.1-linux-arm64.tar.gz"
      sha256 "67b7b91ba439b427f1248cbf29a3f5500fc1e66d53df4965b4eda4b3559264e2"
    end
  end

  def install
    bin.install "eztag"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/eztag -version"))
  end
end
