# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Feedfilter < Formula
  desc "Rss feed filtering tool"
  homepage "https://github.com/cdzombak/feedfilter"
  url "https://github.com/cdzombak/feedfilter/archive/refs/tags/v1.1.0.tar.gz"
  version "1.1.0"
  sha256 "1f3fc8a466f638ab4c4f01998ec0dc1befb0b1a01a69858dd4657b2703a70bb4"
  license "GPL-3.0"

  on_macos do
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/feedfilter/releases/download/v1.1.0/feedfilter-1.1.0-linux-amd64.tar.gz"
      sha256 "d53ea94d47bbc3829eb7f537ccda3e7e2e3c4ad3ca26931a853a2c823eed148f"
    end

    on_arm do
      url "https://github.com/cdzombak/feedfilter/releases/download/v1.1.0/feedfilter-1.1.0-linux-arm64.tar.gz"
      sha256 "732f0279bc6c2a0166ab073bd572c3193d6b09e1f5c0c11ac3ae555289b17c26"
    end
  end

  def install
    bin.install "feedfilter"
  end

  test do
    assert_match("1.1.0", shell_output("#{bin}/feedfilter version"))
  end
end
