# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Feedfilter < Formula
  desc "Rss feed filtering tool"
  homepage "https://github.com/cdzombak/feedfilter"
  url "https://github.com/cdzombak/feedfilter/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "fa4adc6059c6464c3125f3c1d986637f2aa36ba95c5fd44c30abbd52b3c52941"
  license "GPL-3.0"

  on_macos do
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/feedfilter/releases/download/v1.0.0/feedfilter-1.0.0-linux-amd64.tar.gz"
      sha256 "43f5fb26d2e6a7313353a4ed93f42bbbd5e14355885d3ffe366dc4c3201c8fbf"
    end

    on_arm do
      url "https://github.com/cdzombak/feedfilter/releases/download/v1.0.0/feedfilter-1.0.0-linux-arm64.tar.gz"
      sha256 "8f9dfddfb20685b71f634841a93843cda7855080e36864ab592a7d57dd51381b"
    end
  end

  def install
    bin.install "feedfilter"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/feedfilter version"))
  end
end
