# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class FlickrRss < Formula
  desc "Generate an rss feed of a flickr photostream or your friends & family feed"
  homepage "https://github.com/cdzombak/flickr-rss"
  url "https://github.com/cdzombak/flickr-rss/archive/refs/tags/v1.0.4.tar.gz"
  version "1.0.4"
  sha256 "bb1d632ee3f9349a3760ffdcbf46f91b20f58481d7da6ccf97e14bd6c08f58a5"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/flickr-rss/releases/download/v1.0.4/flickr-rss-1.0.4-darwin-amd64.tar.gz"
      sha256 "1142fd9bbe215912ab9d5322cdae7b3a8129fcdfbb1b1178a7c8536abe78aabd"
    end

    on_arm do
      url "https://github.com/cdzombak/flickr-rss/releases/download/v1.0.4/flickr-rss-1.0.4-darwin-arm64.tar.gz"
      sha256 "3aef76673701b4860c2633863500af49ef515447b430b0a24910a62746ed032e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/flickr-rss/releases/download/v1.0.4/flickr-rss-1.0.4-linux-amd64.tar.gz"
      sha256 "2ea88664b442d0bf7c7a066c51683c553db10d2d6bc13811007ea8bbc8626258"
    end

    on_arm do
      url "https://github.com/cdzombak/flickr-rss/releases/download/v1.0.4/flickr-rss-1.0.4-linux-arm64.tar.gz"
      sha256 "f610f3471f2d8c63f56d0dc7a6d066e97ba84aa7b8a7f7f3ff901d215c23ea24"
    end
  end

  def install
    bin.install "flickr-rss"
  end

  test do
    assert_match("1.0.4", shell_output("#{bin}/flickr-rss version"))
  end
end
