# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class FlickrRss < Formula
  desc "Generate an rss feed of a flickr photostream or your flickr friends &amp; family fee"
  homepage "https://github.com/cdzombak/flickr-rss"
  url "https://github.com/cdzombak/flickr-rss/archive/refs/tags/v0.0.3.tar.gz"
  version "0.0.3"
  sha256 "6d40d63b7609e6f7cbb68b230a1bb086b47d292bf97c059ba299278671495080"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/flickr-rss/releases/download/v0.0.3/flickr-rss-0.0.3-darwin-amd64.tar.gz"
      sha256 "71933109144f6088d80a2f2d7bd327b557640cccffb4fbe3101ef81a36306b81"
    end

    on_arm do
      url "https://github.com/cdzombak/flickr-rss/releases/download/v0.0.3/flickr-rss-0.0.3-darwin-arm64.tar.gz"
      sha256 "94c01c2fa56a3b3e00c53da4dcc3411b2802cf5d90696232cece2539f6ed9ef2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/flickr-rss/releases/download/v0.0.3/flickr-rss-0.0.3-linux-amd64.tar.gz"
      sha256 "ecf147bdde749e6693b8480ca6489e4d654ee229118e76f8a5caee616fa40896"
    end

    on_arm do
      url "https://github.com/cdzombak/flickr-rss/releases/download/v0.0.3/flickr-rss-0.0.3-linux-arm64.tar.gz"
      sha256 "8c00dae6d2d07edbcf8ab520ea24944135161683083ba31d675eb3f528377b90"
    end
  end

  def install
    bin.install "flickr-rss"
  end

  test do
    assert_match("0.0.3", shell_output("#{bin}/flickr-rss version"))
  end
end
