# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class FlickrExporter < Formula
  desc "Export all your flickr photos, or a selected set or collection, preserving title"
  homepage "https://github.com/cdzombak/flickr-exporter"
  url "https://github.com/cdzombak/flickr-exporter/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "cf2688a2c58cd5009c7c2e0f259561877fa3931d3e9a16664a64632c277d756e"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/flickr-exporter/releases/download/v1.0.0/flickr-exporter-1.0.0-darwin-amd64.tar.gz"
      sha256 "848b75e850e61b7663fec68549778d9ca400b912fa9f778df541421348dc6a7e"
    end

    on_arm do
      url "https://github.com/cdzombak/flickr-exporter/releases/download/v1.0.0/flickr-exporter-1.0.0-darwin-arm64.tar.gz"
      sha256 "9fe14c5ba4955a09c406607af1f6dfba1d4d6617e24ca1eefffb76825c117e48"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/flickr-exporter/releases/download/v1.0.0/flickr-exporter-1.0.0-linux-amd64.tar.gz"
      sha256 "99fa9dba97daec9573d92c6ff7021669b22fb8e6041fa303bbe74e5197578922"
    end

    on_arm do
      url "https://github.com/cdzombak/flickr-exporter/releases/download/v1.0.0/flickr-exporter-1.0.0-linux-arm64.tar.gz"
      sha256 "01872b37f1aeb9c18d570e839b79ccbc6ac044a6ae84aa830b9c1d89c330fe4a"
    end
  end

  def install
    bin.install "flickr-exporter"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/flickr-exporter --version"))
  end
end
