# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Gallerygen < Formula
  desc "Generate a static html gallery from a directory tree of images"
  homepage "https://github.com/cdzombak/gallerygen"
  url "https://github.com/cdzombak/gallerygen/archive/refs/tags/v1.0.6.tar.gz"
  version "1.0.6"
  sha256 "a045435302fa98d4d525d33468fc222ae20d74e9006831f0c889b17b30aed289"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.6/gallerygen-1.0.6-darwin-amd64.tar.gz"
      sha256 "2c7dde22dab53b3071b390a28dd653aae594255002993a072365de0c1131e6de"
    end

    on_arm do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.6/gallerygen-1.0.6-darwin-arm64.tar.gz"
      sha256 "41ba86e3f71219b0002313253029929b779f4f444ce1a61047725de5bb61075f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.6/gallerygen-1.0.6-linux-amd64.tar.gz"
      sha256 "6c251725b93e77a4b6d703d166d0d7196958f39e80fa6bceedbbeb8ed9590065"
    end

    on_arm do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.6/gallerygen-1.0.6-linux-arm64.tar.gz"
      sha256 "2d0838dedfb161e7017169fe29257ada54bd7df16eb395798c51328ab7310885"
    end
  end

  def install
    bin.install "gallerygen"
  end

  test do
    assert_match("1.0.6", shell_output("#{bin}/gallerygen -version"))
  end
end
