# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Gallerygen < Formula
  desc "Generate a static html gallery from a directory tree of images"
  homepage "https://github.com/cdzombak/gallerygen"
  url "https://github.com/cdzombak/gallerygen/archive/refs/tags/v1.0.3.tar.gz"
  version "1.0.3"
  sha256 "5517ec8aa23ae8213dc07690199039614ccd733a2e5299ccec31ef2266fb050c"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.3/gallerygen-1.0.3-darwin-amd64.tar.gz"
      sha256 "1b55b4587b5bf79ac3f2a9e3332d1321c2a9e8c89a9921e6b9d0453a1b2ce9fb"
    end

    on_arm do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.3/gallerygen-1.0.3-darwin-arm64.tar.gz"
      sha256 "e3e00535f91c08787f390df6761375e4c5619778786805dd463aee8b36196e5a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.3/gallerygen-1.0.3-linux-amd64.tar.gz"
      sha256 "242b52c9e44cc457e60ac078079211e6664f1b8cd941aed7408cf4d3a53c7183"
    end

    on_arm do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.3/gallerygen-1.0.3-linux-arm64.tar.gz"
      sha256 "eb2da07a9a47f19739fc8c62a61eb36e3e508fbab406b63732d762b8da3a0401"
    end
  end

  def install
    bin.install "gallerygen"
  end

  test do
    assert_match("1.0.3", shell_output("#{bin}/gallerygen -version"))
  end
end
