# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Gallerygen < Formula
  desc "Generate a static html gallery from a directory tree of images"
  homepage "https://github.com/cdzombak/gallerygen"
  url "https://github.com/cdzombak/gallerygen/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "280c0160f562edd29959a1824c6a619e457c1ca7700635670106d5ad2d848441"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.1/gallerygen-1.0.1-darwin-amd64.tar.gz"
      sha256 "3550ba0a2b2a9a67d5a9b8dd148b1f5f82a1ffad698c3ca6f6992ae4b5894317"
    end

    on_arm do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.1/gallerygen-1.0.1-darwin-arm64.tar.gz"
      sha256 "8add8a9340cb8c235d9bff302fe8d69be9284a70ce49e776bace107f06fe449f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.1/gallerygen-1.0.1-linux-amd64.tar.gz"
      sha256 "1bbce081d625ab1c7f08b7b683a5ff3750fcff642ef42a92ac8ba4180a8745d5"
    end

    on_arm do
      url "https://github.com/cdzombak/gallerygen/releases/download/v1.0.1/gallerygen-1.0.1-linux-arm64.tar.gz"
      sha256 "ab2ac23df2a837ece9640f7b4bf1876df7bc4efa1059e72374ea9b1db0e564b9"
    end
  end

  def install
    bin.install "gallerygen"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/gallerygen -version"))
  end
end
