# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ghfeed < Formula
  desc "Github activity feed consolidator"
  homepage "https://github.com/cdzombak/ghfeed"
  url "https://github.com/cdzombak/ghfeed/archive/refs/tags/v1.1.0.tar.gz"
  version "1.1.0"
  sha256 "240b9c57d50ddcc2495e8b44e14792bf1268c08ac7248822cfd858243a0d0214"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.1.0/ghfeed-1.1.0-darwin-amd64.tar.gz"
      sha256 "903fac2b701c3568dba32a4f0f67102ef7b54e484ae34c9d030e280776f66701"
    end

    on_arm do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.1.0/ghfeed-1.1.0-darwin-arm64.tar.gz"
      sha256 "0e82e043a8dbd311c9ef0dd3c51287651928a86ad0329379defbe0c8b005def4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.1.0/ghfeed-1.1.0-linux-amd64.tar.gz"
      sha256 "41be24de7b53ebfa0a8cb4869c33d6485bcb318862d62994816b7cf9b1bad3a2"
    end

    on_arm do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.1.0/ghfeed-1.1.0-linux-arm64.tar.gz"
      sha256 "3e17c73da652f5dd35320faf92bf319fa5c155fc0bdce23602c589890941ad5d"
    end
  end

  def install
    bin.install "ghfeed"
  end

  test do
    assert_match("1.1.0", shell_output("#{bin}/ghfeed -version"))
  end
end
