# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ghfeed < Formula
  desc "Github activity feed consolidator"
  homepage "https://github.com/cdzombak/ghfeed"
  url "https://github.com/cdzombak/ghfeed/archive/refs/tags/v1.2.0.tar.gz"
  version "1.2.0"
  sha256 "4ddab94e5319d78aa4e16fec2898ff2c30515399df97583e9ef5b6df07d01777"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.2.0/ghfeed-1.2.0-darwin-amd64.tar.gz"
      sha256 "b12ea494effc70bf42f06ca8707ea5ca237b7bc769ffdec669fb6b636437cc0c"
    end

    on_arm do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.2.0/ghfeed-1.2.0-darwin-arm64.tar.gz"
      sha256 "5e9217900873f8d2b446a6201d36a780e514af24acb5f19dfe81cd059639e8d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.2.0/ghfeed-1.2.0-linux-amd64.tar.gz"
      sha256 "1433dcfa4d2d9238f5cec3b77bb38a6f68b5b83b389c8e3c5a4a873a3bea0727"
    end

    on_arm do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.2.0/ghfeed-1.2.0-linux-arm64.tar.gz"
      sha256 "efd0392b36e5d59c880c01726ef3142d0c822220a10c90b71d5d247f06d005b8"
    end
  end

  def install
    bin.install "ghfeed"
  end

  test do
    assert_match("1.2.0", shell_output("#{bin}/ghfeed -version"))
  end
end
