# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ghfeed < Formula
  desc "Github activity feed consolidator"
  homepage "https://github.com/cdzombak/ghfeed"
  url "https://github.com/cdzombak/ghfeed/archive/refs/tags/v1.4.5.tar.gz"
  version "1.4.5"
  sha256 "a62767405f6f01348301bff0be01471962f0ccbfec36198c2aea0bec7c188edd"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.4.5/ghfeed-1.4.5-darwin-amd64.tar.gz"
      sha256 "038f29df7c63fc04ad899ac6103a57de09bd0ceb4104eb85a8889fd6b6c275ce"
    end

    on_arm do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.4.5/ghfeed-1.4.5-darwin-arm64.tar.gz"
      sha256 "e99ac529c59cedb16592060a57cfad3ef0ec2f76ab9d4df7a4e0fa661b2b6bb7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.4.5/ghfeed-1.4.5-linux-amd64.tar.gz"
      sha256 "9cb66741682d363cf2b96f1641879ad0b7d7760628ca8abfc586ec187a9fbeef"
    end

    on_arm do
      url "https://github.com/cdzombak/ghfeed/releases/download/v1.4.5/ghfeed-1.4.5-linux-arm64.tar.gz"
      sha256 "98743e1a3c73cf859f78ada778fcc6ab0329de46da2fc9b66ba9cf7238872861"
    end
  end

  def install
    bin.install "ghfeed"
  end

  test do
    assert_match("1.4.5", shell_output("#{bin}/ghfeed -version"))
  end
end
