# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitAc < Formula
  desc "Git autocommit: commit staged changes with llm-written commit messages"
  homepage "https://github.com/cdzombak/git-ac"
  url "https://github.com/cdzombak/git-ac/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "16d58454902cd1f69dc03e253b732093e1b7af4365fdc68432f324591a98e728"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.0/git-ac-1.0.0-darwin-amd64.tar.gz"
      sha256 "96921e83b6bc85a7d4f2af41f3e398a50122a0746c938dbcc874464ab0a4b6dc"
    end

    on_arm do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.0/git-ac-1.0.0-darwin-arm64.tar.gz"
      sha256 "ef912636c616b755a0adadb041ae610c7bb58f29134d0529ba2bbe0312baf32b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.0/git-ac-1.0.0-linux-amd64.tar.gz"
      sha256 "4f757bf01dd75d1ad816074ee6d26e28f31668ee58a30609880954cc91625f32"
    end

    on_arm do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.0/git-ac-1.0.0-linux-arm64.tar.gz"
      sha256 "21350eaac02fc9c11749fdbd441014b3baac09edb262e322a21b81481001e517"
    end
  end

  def install
    bin.install "git-ac"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/git-ac -version"))
  end
end
