# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitAc < Formula
  desc "Git autocommit: commit staged changes with llm-written commit messages"
  homepage "https://github.com/cdzombak/git-ac"
  url "https://github.com/cdzombak/git-ac/archive/refs/tags/v1.0.3.tar.gz"
  version "1.0.3"
  sha256 "f1978f43aa628defb686e4dd15d2df48b287a5daa053db550f7fdd6da768a1e7"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.3/git-ac-1.0.3-darwin-amd64.tar.gz"
      sha256 "76729c01142c1c5b803e4d54c012293613b5e65635e4ce6bc644cca9f7d680e3"
    end

    on_arm do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.3/git-ac-1.0.3-darwin-arm64.tar.gz"
      sha256 "eb52ca9a4e92e0d53778a30fe14f80f5634292d5bf8a0557956e7e944cb40b25"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.3/git-ac-1.0.3-linux-amd64.tar.gz"
      sha256 "8823620e6678848d38d2ace6864cb208bf4609045fa5ba1626e7d13f0245465c"
    end

    on_arm do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.3/git-ac-1.0.3-linux-arm64.tar.gz"
      sha256 "5a55bda99957ba9f5cfda0be396d4709a10bed63c011922f562bdb1dc5751ea1"
    end
  end

  def install
    bin.install "git-ac"
  end

  test do
    assert_match("1.0.3", shell_output("#{bin}/git-ac -version"))
  end
end
