# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GitAc < Formula
  desc "Git autocommit: commit staged changes with llm-written commit messages"
  homepage "https://github.com/cdzombak/git-ac"
  url "https://github.com/cdzombak/git-ac/archive/refs/tags/v1.0.4.tar.gz"
  version "1.0.4"
  sha256 "0f5392bd0ffcc54579e9e69da78abc3a4b9a026be7bb0d1166dfead768aa220f"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.4/git-ac-1.0.4-darwin-amd64.tar.gz"
      sha256 "18210c1d07be5a0c601aa3e48d1bc7d4be1f8d1bb62574f61459976ca9fd8605"
    end

    on_arm do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.4/git-ac-1.0.4-darwin-arm64.tar.gz"
      sha256 "0603837273cf8cfba48b31287fb6a97bd75bc8875276b61031f6353893a06b62"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.4/git-ac-1.0.4-linux-amd64.tar.gz"
      sha256 "4daffc9d0b929fc5a577ec6dd30ed4886e179308b892fce7a84f0900a0fd17e5"
    end

    on_arm do
      url "https://github.com/cdzombak/git-ac/releases/download/v1.0.4/git-ac-1.0.4-linux-arm64.tar.gz"
      sha256 "6decfbe15804c5c7e836f66538db8be97f91645e13ffc56cd5854d86779ec879"
    end
  end

  def install
    bin.install "git-ac"
  end

  test do
    assert_match("1.0.4", shell_output("#{bin}/git-ac -version"))
  end
end
