# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GmailCleaner < Formula
  desc "Delete old messages in a chosen label from your gmail account"
  homepage "https://github.com/cdzombak/gmail-cleaner"
  url "https://github.com/cdzombak/gmail-cleaner/archive/refs/tags/v0.0.1.tar.gz"
  sha256 "8981c70f098d630000f1edf45c77fa90babb7ccf6ce11a4b7b19e5ce7376c0ce"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/gmail-cleaner/releases/download/v0.0.1/gmail-cleaner-0.0.1-darwin-amd64.tar.gz"
      sha256 "9feeb006b7002de4440fd76a9e54cb3fb576dcbabf3ffaed082e517355512d1b"
    end

    on_arm do
      url "https://github.com/cdzombak/gmail-cleaner/releases/download/v0.0.1/gmail-cleaner-0.0.1-darwin-arm64.tar.gz"
      sha256 "26a7274bdc612d15c3adefe02ed4cc9602366d8595ca0093f3e59e9c42c952b6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/gmail-cleaner/releases/download/v0.0.1/gmail-cleaner-0.0.1-linux-amd64.tar.gz"
      sha256 "c7be9bb7fad6d03ba6ea144c4c370ab67af2fca07a08b1b4c33a3a21d24ea2e6"
    end

    on_arm do
      url "https://github.com/cdzombak/gmail-cleaner/releases/download/v0.0.1/gmail-cleaner-0.0.1-linux-arm64.tar.gz"
      sha256 "47d775eb3c4346a18390108dbefea6b9f8d0a958dd228c27ec1c4af4021f775c"
    end
  end

  def install
    bin.install "gmail-cleaner"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/gmail-cleaner -version"))
  end
end
