# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class HostsTimer < Formula
  desc "Block websites on your system with /etc/hosts, and re-enable them on demand for"
  homepage "https://github.com/cdzombak/hosts-timer"
  url "https://github.com/cdzombak/hosts-timer/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "ef71aa7a9a29c9ab4a8144f4d16dfd8c9c5379fb74736145f63c6738967937fc"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/hosts-timer/releases/download/v1.0.0/hosts-timer-1.0.0-darwin-amd64.tar.gz"
      sha256 "1e9e73182a95a5baf5852bfff511d80b26701f338ce1f53c6360da2bc305264a"
    end

    on_arm do
      url "https://github.com/cdzombak/hosts-timer/releases/download/v1.0.0/hosts-timer-1.0.0-darwin-arm64.tar.gz"
      sha256 "a418bbd05b02f6e8543b3cfa0af72b3d8e8e48d34d49fb76ccd52c12885823ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/hosts-timer/releases/download/v1.0.0/hosts-timer-1.0.0-linux-amd64.tar.gz"
      sha256 "76488d763eb1bac14159be09278cb0c6b647c98f8304eb70999f468e99c25757"
    end

    on_arm do
      url "https://github.com/cdzombak/hosts-timer/releases/download/v1.0.0/hosts-timer-1.0.0-linux-arm64.tar.gz"
      sha256 "e66d960b7219ece838eede73dbc01236c860ff0048221bb8782ac77269248ae6"
    end
  end

  def install
    bin.install "hosts-timer"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/hosts-timer -version"))
  end
end
