# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class HumidityReminder < Formula
  desc "Get email reminders when the ideal indoor humidity changes"
  homepage "https://github.com/cdzombak/humidity-reminder"
  url "https://github.com/cdzombak/humidity-reminder/archive/refs/tags/v1.0.2.tar.gz"
  version "1.0.2"
  sha256 "8cb8de524f9955eb4ecca1cd37a9a0bea66f356949c70e3755f38d4b8a7a1920"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/humidity-reminder/releases/download/v1.0.2/humidity-reminder-1.0.2-darwin-amd64.tar.gz"
      sha256 "5b108a8637ba54d915579f04fe56bbe801b9a48390e12efcb8f08431fb0628f7"
    end

    on_arm do
      url "https://github.com/cdzombak/humidity-reminder/releases/download/v1.0.2/humidity-reminder-1.0.2-darwin-arm64.tar.gz"
      sha256 "e1ae72e4a2671c46a5fa0a90fb345b8e0dd85563360a1a08dc085a2428fa54b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/humidity-reminder/releases/download/v1.0.2/humidity-reminder-1.0.2-linux-amd64.tar.gz"
      sha256 "fafa353b17ce000d4033b7c2a13bdd7b11de12b192b2b9da06f2eef8b339acf9"
    end

    on_arm do
      url "https://github.com/cdzombak/humidity-reminder/releases/download/v1.0.2/humidity-reminder-1.0.2-linux-arm64.tar.gz"
      sha256 "9db53c3e3bfda28332c7968f72c3894301990b44ad45c1cde138039832f6a4bf"
    end
  end

  def install
    bin.install "humidity-reminder"
  end

  test do
    assert_match("1.0.2", shell_output("#{bin}/humidity-reminder -version"))
  end
end
