# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class HumidityReminder < Formula
  desc "Get email reminders when the ideal indoor humidity changes"
  homepage "https://github.com/cdzombak/humidity-reminder"
  url "https://github.com/cdzombak/humidity-reminder/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "f29c9560fd1a4645145ad2b9f6e21c9327a47871c8fd59d0ffe1f88bfb9e5709"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/humidity-reminder/releases/download/v1.0.1/humidity-reminder-1.0.1-darwin-amd64.tar.gz"
      sha256 "00fd8bbc07850e704836381cd82331150223cd1f790562c5219278183d043fec"
    end

    on_arm do
      url "https://github.com/cdzombak/humidity-reminder/releases/download/v1.0.1/humidity-reminder-1.0.1-darwin-arm64.tar.gz"
      sha256 "b58c5edbeab20cb65e3510f17b6807d546afee29efa27b1b02e9d49e2841a9b3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/humidity-reminder/releases/download/v1.0.1/humidity-reminder-1.0.1-linux-amd64.tar.gz"
      sha256 "b06a5f6d38f2a723766f74bd872519d80270ae8f3ff2634fe7f518ce9ffac940"
    end

    on_arm do
      url "https://github.com/cdzombak/humidity-reminder/releases/download/v1.0.1/humidity-reminder-1.0.1-linux-arm64.tar.gz"
      sha256 "c35f31a0f12ef70954188041ab64f04834336c87f033f4655d037030705cc6a5"
    end
  end

  def install
    bin.install "humidity-reminder"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/humidity-reminder -version"))
  end
end
