# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class IpcamBrowser < Formula
  desc "Improved media browser for sd card storage on sv3c/camhipro compatible ip webcam"
  homepage "https://github.com/cdzombak/ipcam-browser"
  url "https://github.com/cdzombak/ipcam-browser/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "f160d4f5354546c1e658df8d640e4f8db69790be26c31f6b36e266168fee5e8d"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/ipcam-browser/releases/download/v1.0.0/ipcam-browser-1.0.0-darwin-amd64.tar.gz"
      sha256 "e6188baf5bb7385680b5793013a2b86fe7ed2b05d3fa46de1729f160936840b4"
    end

    on_arm do
      url "https://github.com/cdzombak/ipcam-browser/releases/download/v1.0.0/ipcam-browser-1.0.0-darwin-arm64.tar.gz"
      sha256 "400cb592182f50ce29b36b047e373128165e3d43a4ea853f38b81f4df4693b1f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/ipcam-browser/releases/download/v1.0.0/ipcam-browser-1.0.0-linux-amd64.tar.gz"
      sha256 "ee69cdd96eac009130800d4481c5e73a6f44bad3e2e7c249f69e4af832a57620"
    end

    on_arm do
      url "https://github.com/cdzombak/ipcam-browser/releases/download/v1.0.0/ipcam-browser-1.0.0-linux-arm64.tar.gz"
      sha256 "c772a44fbdfd7ffa65dffdbd22bb4c766b9cd29ebba8567746fdd21971ec4127"
    end
  end

  def install
    bin.install "ipcam-browser"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/ipcam-browser -version"))
  end
end
