# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class IpcamBrowser < Formula
  desc "Improved media browser for sd card storage on sv3c/camhipro compatible ip webcam"
  homepage "https://github.com/cdzombak/ipcam-browser"
  url "https://github.com/cdzombak/ipcam-browser/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "fe9a505bcf5db46910f43c2e1e9d8960b76504fbe27b7e2b3f464a5cc5fcfa6c"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/ipcam-browser/releases/download/v0.0.1/ipcam-browser-0.0.1-darwin-amd64.tar.gz"
      sha256 "f69a5a4e53941d4d1879f7b889a4db7795701efeea6ca95da384fcfeb8f7cbd7"
    end

    on_arm do
      url "https://github.com/cdzombak/ipcam-browser/releases/download/v0.0.1/ipcam-browser-0.0.1-darwin-arm64.tar.gz"
      sha256 "9ba6fabc31a753a43537cc422a04c44bf036bc969bbedea037d558f636b9ad1c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/ipcam-browser/releases/download/v0.0.1/ipcam-browser-0.0.1-linux-amd64.tar.gz"
      sha256 "24a99ddc5939b840d8d3a5a772eaa52b5d3dcf5a6fc6e66c869108d985455543"
    end

    on_arm do
      url "https://github.com/cdzombak/ipcam-browser/releases/download/v0.0.1/ipcam-browser-0.0.1-linux-arm64.tar.gz"
      sha256 "8faa04b92bb6a226d1d6cac0ab00031164fe244ee2dfeb06c9c899031fa0791b"
    end
  end

  def install
    bin.install "ipcam-browser"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/ipcam-browser -version"))
  end
end
