# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Listening < Formula
  desc "List processes listening for network connections listening is an easy-to-use, c"
  homepage "https://github.com/cdzombak/listening"
  url "https://github.com/cdzombak/listening/archive/v0.0.2.tar.gz"
  sha256 "44fadc70390dbf63774e5932d18a1612cfcc25fc0c907437dc1d89fc7f05fcdd"
  license "LGPL-3.0"

  def install
    bin.install "listening"
  end

  test do
    assert_match("0.0.2", shell_output("#{bin}/listening -version"))
  end
end
