# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Listening < Formula
  desc "List processes listening for network connections listening is an easy-to-use, c"
  homepage "https://github.com/cdzombak/listening"
  url "https://github.com/cdzombak/listening/archive/v1.0.0.tar.gz"
  sha256 "665c536002199cc7c9decdca2431b4a5c2c582fe0427c7fe3989ba222aa59bfe"
  license "LGPL-3.0"

  def install
    bin.install "listening"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/listening -version"))
  end
end
