# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeAiOrganizer < Formula
  desc "Use local llms to organize your unsorted photos in lychee"
  homepage "https://github.com/cdzombak/lychee-ai-organizer"
  url "https://github.com/cdzombak/lychee-ai-organizer/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "108ea96270c273a0b3365fa0a38bfc5e1b510a9080ddd0db9e22e5985f7317d1"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.0.1/lychee-ai-organizer-1.0.1-darwin-amd64.tar.gz"
      sha256 "c0db3f8cceb88bf094eb1eb6125eb3bf6667a561ccbedccc1ce3127e922b8ab9"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.0.1/lychee-ai-organizer-1.0.1-darwin-arm64.tar.gz"
      sha256 "b4e5eabf1692fbf6371c3be15f1f850f105160860d97abff64ea45492fc3f466"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.0.1/lychee-ai-organizer-1.0.1-linux-amd64.tar.gz"
      sha256 "522d9579837604631e571f410c419366fd6cdd9a5c7440e48c0b074b3cc14da9"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.0.1/lychee-ai-organizer-1.0.1-linux-arm64.tar.gz"
      sha256 "14892124aea561cb90d655abb133944ef48dc5fc68ada26c0ea4cbc3369e046d"
    end
  end

  def install
    bin.install "lychee-ai-organizer"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/lychee-ai-organizer -version"))
  end
end
