# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeBwTagger < Formula
  desc "Tag the black & white photos in your lychee photo library"
  homepage "https://github.com/cdzombak/lychee-bw-tagger"
  url "https://github.com/cdzombak/lychee-bw-tagger/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "301d9f26c3eb7c85c69d743c2a6adf3ad0775b8202c0a3b77cdfdbf3acfbfdea"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-bw-tagger/releases/download/v0.0.1/lychee-bw-tagger-0.0.1-darwin-amd64.tar.gz"
      sha256 "a8d81754f2cadf5a2fbfd1ea4f9c0ee76d218780d1a5d4e80e495d1e70c57440"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-bw-tagger/releases/download/v0.0.1/lychee-bw-tagger-0.0.1-darwin-arm64.tar.gz"
      sha256 "c50c9a4180b230e3fd155bd4905f02e84c459f5d11d62cec6a5710a134675bd8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-bw-tagger/releases/download/v0.0.1/lychee-bw-tagger-0.0.1-linux-amd64.tar.gz"
      sha256 "7c0cd577873f141272989f5a64bb20072bae290ae6a7d0f5490a0ebb18eead67"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-bw-tagger/releases/download/v0.0.1/lychee-bw-tagger-0.0.1-linux-arm64.tar.gz"
      sha256 "3ca61e73ea3cc6593f95cebb6655760790593578b69c5237f23a976a222f2da4"
    end
  end

  def install
    bin.install "lychee-bw-tagger"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/lychee-bw-tagger -version"))
  end
end
