# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeAiOrganizer < Formula
  desc "Use local llms to organize your unsorted photos in lychee"
  homepage "https://github.com/cdzombak/lychee-ai-organizer"
  url "https://github.com/cdzombak/lychee-ai-organizer/archive/refs/tags/v1.1.1.tar.gz"
  version "1.1.1"
  sha256 "e864cdc8ba9541ee7ed648ca4d81e6a2be86124a2d173f36ccdf9de5cb5d7576"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.1/lychee-ai-organizer-1.1.1-darwin-amd64.tar.gz"
      sha256 "f62d0a234377230e49f309601f33e7c7c6411c571cb19374a2cb94563c50ed34"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.1/lychee-ai-organizer-1.1.1-darwin-arm64.tar.gz"
      sha256 "de14c4aa441e3d810c0f669640b8f1af6a39c2c926d02bb5ddcd2e2c4330cc3e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.1/lychee-ai-organizer-1.1.1-linux-amd64.tar.gz"
      sha256 "0108902b10227c3a32e74c6ef3e64f6e26ada527dd31e6defde5e56d1c6aa776"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.1/lychee-ai-organizer-1.1.1-linux-arm64.tar.gz"
      sha256 "764a7b78e69bb3fbfc8b81bb5eafe9527798cf3b092b6dd8cda16353c04c41e7"
    end
  end

  def install
    bin.install "lychee-ai-organizer"
  end

  test do
    assert_match("1.1.1", shell_output("#{bin}/lychee-ai-organizer -version"))
  end
end
