# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeMetaTool < Formula
  desc "Quickly find & edit untitled photos in your lychee photo library"
  homepage "https://github.com/cdzombak/lychee-meta-tool"
  url "https://github.com/cdzombak/lychee-meta-tool/archive/refs/tags/v1.1.2.tar.gz"
  version "1.1.2"
  sha256 "17675d9de77172be455f928a400724266fb37a9a7c823435e7a5eb037ff4c433"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.2/lychee-meta-tool-1.1.2-darwin-amd64.tar.gz"
      sha256 "b1d2e339ea996e0a4032fe6247e8c2bcf6b3e826a3ce2e3fc468f815742c3b24"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.2/lychee-meta-tool-1.1.2-darwin-arm64.tar.gz"
      sha256 "4bc6e677a3e080de404054e2515cc6b72f47ce0646e965376595bef521c78bcd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.2/lychee-meta-tool-1.1.2-linux-amd64.tar.gz"
      sha256 "c2c5dd7ce27ea6a61a2a6a386c94cbe9541091091649f8f19762086d17fe8341"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.2/lychee-meta-tool-1.1.2-linux-arm64.tar.gz"
      sha256 "0bde3af672690eb961b3573f399b8a69506112c3dd25c941ad11e43070a3bd4d"
    end
  end

  def install
    bin.install "lychee-meta-tool"
  end

  test do
    assert_match("1.1.2", shell_output("#{bin}/lychee-meta-tool version"))
  end
end
