# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeAiOrganizer < Formula
  desc "Use local llms to organize your unsorted photos in lychee"
  homepage "https://github.com/cdzombak/lychee-ai-organizer"
  url "https://github.com/cdzombak/lychee-ai-organizer/archive/refs/tags/v1.1.0.tar.gz"
  version "1.1.0"
  sha256 "bc1e305590e4303d9589b9e3133d935333dd62e3755133e99bc8b0f5030d1c62"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.0/lychee-ai-organizer-1.1.0-darwin-amd64.tar.gz"
      sha256 "0ab89304f115263cc9f615571f9537858e3f01320a24b6b327cc7359b66edb7b"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.0/lychee-ai-organizer-1.1.0-darwin-arm64.tar.gz"
      sha256 "6ca3c4d43186555258ce6c248e2efad8dbc616e25c7ecd30f93bcb8d95564859"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.0/lychee-ai-organizer-1.1.0-linux-amd64.tar.gz"
      sha256 "964fba543fdb41d9335cc269fc3e5f136610cb25d5ca74965406d68807fd1698"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.0/lychee-ai-organizer-1.1.0-linux-arm64.tar.gz"
      sha256 "aeba44dad0f34f0ba945e45678b3661f785f2091a5f39643a8b08ab06cc01ad2"
    end
  end

  def install
    bin.install "lychee-ai-organizer"
  end

  test do
    assert_match("1.1.0", shell_output("#{bin}/lychee-ai-organizer -version"))
  end
end
