# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeBwTagger < Formula
  desc "Tag the black & white photos in your lychee photo library"
  homepage "https://github.com/cdzombak/lychee-bw-tagger"
  url "https://github.com/cdzombak/lychee-bw-tagger/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "351aa27d683ff244364975a61a416957c311d751bc97be1971cfca7d639b4266"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-bw-tagger/releases/download/v1.0.0/lychee-bw-tagger-1.0.0-darwin-amd64.tar.gz"
      sha256 "8391396afab4067813d89a0f88a7888d1ee8fa705c8105553b0120017cff2428"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-bw-tagger/releases/download/v1.0.0/lychee-bw-tagger-1.0.0-darwin-arm64.tar.gz"
      sha256 "4024c03cea0a223a04efca858d080104e2ab60b95fb06968a68790e1556cfd0a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-bw-tagger/releases/download/v1.0.0/lychee-bw-tagger-1.0.0-linux-amd64.tar.gz"
      sha256 "a3e1249fe5f3b44a9ebb1c0d5567fd035179091e9069b6eb710aaa8a0f139c54"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-bw-tagger/releases/download/v1.0.0/lychee-bw-tagger-1.0.0-linux-arm64.tar.gz"
      sha256 "c3286ef59b0a74f24cffd636269d858e298c32e68505e7cf90ba96e05ada7285"
    end
  end

  def install
    bin.install "lychee-bw-tagger"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/lychee-bw-tagger -version"))
  end
end
