# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeAiOrganizer < Formula
  desc "Use local llms to organize your unsorted photos in lychee"
  homepage "https://github.com/cdzombak/lychee-ai-organizer"
  url "https://github.com/cdzombak/lychee-ai-organizer/archive/refs/tags/v1.1.2.tar.gz"
  version "1.1.2"
  sha256 "d35178ef563930330c0d1f03d3c88c4357811489b96523130d85959ad597430f"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.2/lychee-ai-organizer-1.1.2-darwin-amd64.tar.gz"
      sha256 "5228afc3b0b8c0b50f2039b9e20a3d991f3376f02ae8fa54d050215863fb4e04"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.2/lychee-ai-organizer-1.1.2-darwin-arm64.tar.gz"
      sha256 "a123af60afc9e1ed5324bf8233451d0e96545df737b50dcc0c8d0f358f2da8b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.2/lychee-ai-organizer-1.1.2-linux-amd64.tar.gz"
      sha256 "06574403fcbbb95ce518107cd45ad4cd55c4607bb4fa726f227603d8dd00fc06"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-ai-organizer/releases/download/v1.1.2/lychee-ai-organizer-1.1.2-linux-arm64.tar.gz"
      sha256 "2ab9678f0b2df3fcb25cd3e3132cfcc730b5405b8a7b410d082c3652ed4759db"
    end
  end

  def install
    bin.install "lychee-ai-organizer"
  end

  test do
    assert_match("1.1.2", shell_output("#{bin}/lychee-ai-organizer -version"))
  end
end
