# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeMetaTool < Formula
  desc "Quickly find & edit untitled photos in your lychee photo library"
  homepage "https://github.com/cdzombak/lychee-meta-tool"
  url "https://github.com/cdzombak/lychee-meta-tool/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "0d2afae393cf5cb8eb6b4526c684c422e514cb578a6c37efaa52f90c21f33add"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.0.1/lychee-meta-tool-1.0.1-darwin-amd64.tar.gz"
      sha256 "383f277f37d11b6c3ad0c529372ef04688ccf8cc61a6649ce43c02613a07edde"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.0.1/lychee-meta-tool-1.0.1-darwin-arm64.tar.gz"
      sha256 "d4c0fed7978524ae13459d1c7cb662054df8a1ed0ad41d62609b2b548171571b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.0.1/lychee-meta-tool-1.0.1-linux-amd64.tar.gz"
      sha256 "3f00e0c3ad71491c18b473fa9b3a0a87a6401b203f2966c1258359c02c9fb40a"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.0.1/lychee-meta-tool-1.0.1-linux-arm64.tar.gz"
      sha256 "6e7b9f65cc5a8f27e5896e284cfb087262aebe7b7ce9eb85e097da3d747d7b7a"
    end
  end

  def install
    bin.install "lychee-meta-tool"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/lychee-meta-tool version"))
  end
end
