# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeMetaTool < Formula
  desc "Quickly find & edit untitled photos in your lychee photo library"
  homepage "https://github.com/cdzombak/lychee-meta-tool"
  url "https://github.com/cdzombak/lychee-meta-tool/archive/refs/tags/v1.1.0.tar.gz"
  version "1.1.0"
  sha256 "a439a30e2877f5fb6b9ddbb6ff2c548785497c595dbdc273bff6bb216ee2f432"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.0/lychee-meta-tool-1.1.0-darwin-amd64.tar.gz"
      sha256 "aa2a4eceadd70776711a887e468d1e58fcfa7951d9c21d4b090b5426a7cae075"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.0/lychee-meta-tool-1.1.0-darwin-arm64.tar.gz"
      sha256 "ad10d0b03dd231ee8ee722e655d4035337a1f5543882450c3df8c82579b9d91d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.0/lychee-meta-tool-1.1.0-linux-amd64.tar.gz"
      sha256 "08194af5e4d6fcc82de774aee7b6f869e40ce5fcbb8032f5a9b14d332edc7910"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.0/lychee-meta-tool-1.1.0-linux-arm64.tar.gz"
      sha256 "f694de00e41b29eba6edffad2d50e0ec6c8f5eeb8be48ad1b6c279e4cc5f142c"
    end
  end

  def install
    bin.install "lychee-meta-tool"
  end

  test do
    assert_match("1.1.0", shell_output("#{bin}/lychee-meta-tool version"))
  end
end
