# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeMetaTool < Formula
  desc "Quickly find & edit untitled photos in your lychee photo library"
  homepage "https://github.com/cdzombak/lychee-meta-tool"
  url "https://github.com/cdzombak/lychee-meta-tool/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "e0c65a7d785313fdc480f7c818af36f4987211a57c3a22195c4b382cf0455900"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.0.0/lychee-meta-tool-1.0.0-darwin-amd64.tar.gz"
      sha256 "536630c2ffe865bf03b58ebe28acef1a317fe09f8ca1100456edee87461bc153"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.0.0/lychee-meta-tool-1.0.0-darwin-arm64.tar.gz"
      sha256 "c56ac9577f798da12182525391766ae38b605fb5a40cce532fc2029bb924e7bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.0.0/lychee-meta-tool-1.0.0-linux-amd64.tar.gz"
      sha256 "00f90bceb866d6e34f65cccadcae0063f30c208640d8b90aee407c54ae9a456c"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.0.0/lychee-meta-tool-1.0.0-linux-arm64.tar.gz"
      sha256 "b21ac2d2d19df0a1c27dee12e496e5996a25101e5639860cecc0b40f98588fd4"
    end
  end

  def install
    bin.install "lychee-meta-tool"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/lychee-meta-tool version"))
  end
end
