# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LycheeMetaTool < Formula
  desc "Quickly find & edit untitled photos in your lychee photo library"
  homepage "https://github.com/cdzombak/lychee-meta-tool"
  url "https://github.com/cdzombak/lychee-meta-tool/archive/refs/tags/v1.1.1.tar.gz"
  version "1.1.1"
  sha256 "abc46f92d0a2020709f9646aea4b06e7e3d356085342ee7fbacad179011b1f68"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.1/lychee-meta-tool-1.1.1-darwin-amd64.tar.gz"
      sha256 "78c2b3168381323833cbdee0eeddf36a732a21d5ba618db651e4249a8ebc7b7f"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.1/lychee-meta-tool-1.1.1-darwin-arm64.tar.gz"
      sha256 "c00b3fbb582962bfa3d6184fbc6ae651d50d8c75fbd3a7a493520965c32d219b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.1/lychee-meta-tool-1.1.1-linux-amd64.tar.gz"
      sha256 "a7270e0ec643e49c41590b3c1aa732fbe8101c6d40b57aa1c73de9e3dc8cc5c1"
    end

    on_arm do
      url "https://github.com/cdzombak/lychee-meta-tool/releases/download/v1.1.1/lychee-meta-tool-1.1.1-linux-arm64.tar.gz"
      sha256 "75abfa6a28bff7abdc830428badf07a9f57e44fbf3eacd19543e33ed14db91aa"
    end
  end

  def install
    bin.install "lychee-meta-tool"
  end

  test do
    assert_match("1.1.1", shell_output("#{bin}/lychee-meta-tool version"))
  end
end
