# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MacInstall < Formula
  desc "Idempotent software suite installer for macos"
  homepage "https://github.com/cdzombak/mac-install"
  url "https://github.com/cdzombak/mac-install/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "8bd9448867e79e5d6baa65eb471e43e309e6ead953c19c5b661ef1d7ed2e384f"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mac-install/releases/download/v0.0.1/mac-install-0.0.1-darwin-amd64.tar.gz"
      sha256 "8602387b7a4d87a8bd3453a180e4bd18708607a6e9f2099081a0edf959913abf"
    end

    on_arm do
      url "https://github.com/cdzombak/mac-install/releases/download/v0.0.1/mac-install-0.0.1-darwin-arm64.tar.gz"
      sha256 "0414dd1f9f07b63f158c9827b1a8044defc913e64dbf869103a433d8215888c3"
    end
  end

  def install
    bin.install "mac-install"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/mac-install -version"))
  end
end
