# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MacosUpsInfluxConnector < Formula
  desc "Ship basic ups stats from macos to influxdb"
  homepage "https://github.com/cdzombak/macos-ups-influx-connector"
  url "https://github.com/cdzombak/macos-ups-influx-connector/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "50517e47e1741fe03856c89d1ecc951fb332854d63f05ea424ba059b3ee2f6d0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/macos-ups-influx-connector/releases/download/v1.0.0/macos-ups-influx-connector-1.0.0-darwin-amd64.tar.gz"
      sha256 "22f80257f5f775995d1d7aa6e3c64a3cb92b593748fca664f06f159553ccdfa6"
    end

    on_arm do
      url "https://github.com/cdzombak/macos-ups-influx-connector/releases/download/v1.0.0/macos-ups-influx-connector-1.0.0-darwin-arm64.tar.gz"
      sha256 "409c444c1c87d68a70cc29677ce466360fe7966c0a21e7fcb1ab8de9b006584e"
    end
  end

  def install
    bin.install "macos-ups-influx-connector"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/macos-ups-influx-connector -version"))
  end
end
