# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MacosUpsMqttConnector < Formula
  desc "Send current ups status from your mac to mqtt"
  homepage "https://github.com/cdzombak/macos-ups-mqtt-connector"
  url "https://github.com/cdzombak/macos-ups-mqtt-connector/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "b8f26e7557032edb9d936c0e8c1eff5e0aa13ba128fe88bedfbb9737e9c7ad1b"
  license "MIT"

  def install
    bin.install "macos-ups-mqtt-connector"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/macos-ups-mqtt-connector -version"))
  end
end
