# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MailtoThings < Formula
  desc "Allow sending emails to thingsapp with attachments (kind of)"
  homepage "https://github.com/cdzombak/mailto-things"
  url "https://github.com/cdzombak/mailto-things/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "385a46e4cf977f17d005071472c265d9029ec45af1379b95b7a1df000a3ccf27"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mailto-things/releases/download/v1.0.0/mailto-things-1.0.0-darwin-amd64.tar.gz"
      sha256 "3a6c6c94fd6a50f3c3d17c0613f2dfc12ed9d2607563e0eb6109c2ef71b1fcfd"
    end

    on_arm do
      url "https://github.com/cdzombak/mailto-things/releases/download/v1.0.0/mailto-things-1.0.0-darwin-arm64.tar.gz"
      sha256 "9b2404db0bbf22f7e93d30ce33af86763f5a24445c8b93d9f5c5cef76886d13d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/mailto-things/releases/download/v1.0.0/mailto-things-1.0.0-linux-amd64.tar.gz"
      sha256 "344e8b60f6d1a976e291b37f992adec70602a217bd326fb97b89eabad20a5bf7"
    end

    on_arm do
      url "https://github.com/cdzombak/mailto-things/releases/download/v1.0.0/mailto-things-1.0.0-linux-arm64.tar.gz"
      sha256 "de3e6bfc90ce446b0d5b75a5ac343b00a5cf3bebe7e95958b87ab42a58c24f02"
    end
  end

  def install
    bin.install "mailto-things"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/mailto-things -version"))
  end
end
