# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MastodonPost < Formula
  desc "Simplest possible cli tool for posting to mastodon"
  homepage "https://github.com/cdzombak/mastodon-post"
  url "https://github.com/cdzombak/mastodon-post/archive/v1.0.0.tar.gz"
  sha256 "37934d4f6ff0beff6e0a0062f6f1568edd3c063258da085f7040af806da6df88"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mastodon-post/releases/download/v1.0.0/mastodon-post-1.0.0-darwin-amd64.tar.gz"
      sha256 "9e78693a37ca3f74fcd71199821e5f470f788372f80415fece8c31d136bb2cca"
    end

    on_arm do
      url "https://github.com/cdzombak/mastodon-post/releases/download/v1.0.0/mastodon-post-1.0.0-darwin-arm64.tar.gz"
      sha256 "99fd6d69357029220f0dca2bd1f0f328d58308cb59b1e02fb328bf6e2d530841"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/mastodon-post/releases/download/v1.0.0/mastodon-post-1.0.0-linux-amd64.tar.gz"
      sha256 "473a87d9ce4941b7c134ed31df00ffb33ac544086a6c3b84510362d5619ec679"
    end

    on_arm do
      url "https://github.com/cdzombak/mastodon-post/releases/download/v1.0.0/mastodon-post-1.0.0-linux-arm64.tar.gz"
      sha256 "a86ffcb2c19e8669294d6738dca1f774ce85cab92b75a75e89c6f7e2a4d07f2b"
    end
  end

  def install
    bin.install "mastodon-post"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/mastodon-post -version"))
  end
end
