# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mdunwrap < Formula
  desc "Remove unnecessary line breaks from markdown text"
  homepage "https://github.com/cdzombak/mdunwrap"
  url "https://github.com/cdzombak/mdunwrap/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "4677546e913e58c2a6e41df35471aab23021bec8327e951539390ac39c4a3bfa"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mdunwrap/releases/download/v0.0.1/mdunwrap-0.0.1-darwin-amd64.tar.gz"
      sha256 "50f94fb793e909415f12fb019456cc50d1abfa5730bd314358b09d28cbfe5bdd"
    end

    on_arm do
      url "https://github.com/cdzombak/mdunwrap/releases/download/v0.0.1/mdunwrap-0.0.1-darwin-arm64.tar.gz"
      sha256 "20a882e1e29d85c346a74178b183aa82e833db01e73b4ee791f7c3b4dd119315"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/mdunwrap/releases/download/v0.0.1/mdunwrap-0.0.1-linux-amd64.tar.gz"
      sha256 "6ad5c13806be4936ef1662f36c229df6f66aaf3cd7d27b0a732a21afd6871475"
    end

    on_arm do
      url "https://github.com/cdzombak/mdunwrap/releases/download/v0.0.1/mdunwrap-0.0.1-linux-arm64.tar.gz"
      sha256 "bd0c2fdac8f7af768d78ca6b42988c6c22ecd3729a65bd39e8eb794f3652217d"
    end
  end

  def install
    bin.install "mdunwrap"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/mdunwrap -version"))
  end
end
