# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mqttwxenrich < Formula
  desc "Enrich mqtt messages from weather sensors with unit conversion and supplemental"
  homepage "https://github.com/cdzombak/mqttwxenrich"
  url "https://github.com/cdzombak/mqttwxenrich/archive/refs/tags/v0.0.3.tar.gz"
  version "0.0.3"
  sha256 "d70bdcc43b29f81f1cf9f2b42718804004dcbd9c004b0a1be3d4cab4c5654f6e"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mqttwxenrich/releases/download/v0.0.3/mqttwxenrich-0.0.3-darwin-amd64.tar.gz"
      sha256 "d8951c29b5f0c0718765edc642c96c3b2e4aa53ccd87d7ee141be5689ef37432"
    end

    on_arm do
      url "https://github.com/cdzombak/mqttwxenrich/releases/download/v0.0.3/mqttwxenrich-0.0.3-darwin-arm64.tar.gz"
      sha256 "7b6dc261ecf169d24f39e25bdd723ad3085ac5a100020b2b262f008cd3572bc4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/mqttwxenrich/releases/download/v0.0.3/mqttwxenrich-0.0.3-linux-amd64.tar.gz"
      sha256 "2d797d27407c10ca025d04b3921d476190f80a5d31aba76476d2fe5be7bb7638"
    end

    on_arm do
      url "https://github.com/cdzombak/mqttwxenrich/releases/download/v0.0.3/mqttwxenrich-0.0.3-linux-arm64.tar.gz"
      sha256 "d470214e9cb306b3f546aae795e88cd1f1e59efd3d1ca54b3d25e3318736cca2"
    end
  end

  def install
    bin.install "mqttwxenrich"
  end

  test do
    assert_match("0.0.3", shell_output("#{bin}/mqttwxenrich -version"))
  end
end
