# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mqtt2influxdb < Formula
  desc "Opinionated and intentionally scope-limited mqtt to influxdb bridge"
  homepage "https://github.com/cdzombak/mqtt2influxdb"
  url "https://github.com/cdzombak/mqtt2influxdb/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "3bd56265d64bc750e3a8724727488f55cfc3cbb36187cfb72dcd2cf550f4ed50"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v1.0.1/mqtt2influxdb-1.0.1-darwin-amd64.tar.gz"
      sha256 "2317d8d542443eabff640201a5f24b23ca8673cf74f1a06def26204688a575e2"
    end

    on_arm do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v1.0.1/mqtt2influxdb-1.0.1-darwin-arm64.tar.gz"
      sha256 "90ebe9492e34cf79f5292a3a7d7777e942f7021ce16802949b1e943df9814263"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v1.0.1/mqtt2influxdb-1.0.1-linux-amd64.tar.gz"
      sha256 "1af746e6f471ff4ba952f20affe60803ba6339ed07fe07470394f8c5946db137"
    end

    on_arm do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v1.0.1/mqtt2influxdb-1.0.1-linux-arm64.tar.gz"
      sha256 "0bcc5f4205c743120b464f298c39b733a62ea924c33f3c8983192db655e511d9"
    end
  end

  def install
    bin.install "mqtt2influxdb"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/mqtt2influxdb -version"))
  end
end
