# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mqttwxenrich < Formula
  desc "Enrich mqtt messages from weather sensors with unit conversion and supplemental"
  homepage "https://github.com/cdzombak/mqttwxenrich"
  url "https://github.com/cdzombak/mqttwxenrich/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "5a9eecbdd15901375978765a897d3182efcb8c3087c824681374650f901b64ea"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mqttwxenrich/releases/download/v0.0.1/mqttwxenrich-0.0.1-darwin-amd64.tar.gz"
      sha256 "6c4d3129b5c78f8e7e0b0dd62b0d6411837088e9c97d7a6bf174a4f27243b0a2"
    end

    on_arm do
      url "https://github.com/cdzombak/mqttwxenrich/releases/download/v0.0.1/mqttwxenrich-0.0.1-darwin-arm64.tar.gz"
      sha256 "5689314ece2570b480026bfcf084510ad22083b4753c323e9f28af1f1a35941f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/mqttwxenrich/releases/download/v0.0.1/mqttwxenrich-0.0.1-linux-amd64.tar.gz"
      sha256 "4d4be37dec1b665d2a606888bccef1ecbdaba8d2950423547953a5d030d029d2"
    end

    on_arm do
      url "https://github.com/cdzombak/mqttwxenrich/releases/download/v0.0.1/mqttwxenrich-0.0.1-linux-arm64.tar.gz"
      sha256 "d21d483e082debdc8d59fc70a357bb75ef4af51078fab68b32b04689953956bb"
    end
  end

  def install
    bin.install "mqttwxenrich"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/mqttwxenrich -version"))
  end
end
