# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mqtt2ntfy < Formula
  desc "Mqtt to ntfy bridge"
  homepage "https://github.com/cdzombak/mqtt2ntfy"
  url "https://github.com/cdzombak/mqtt2ntfy/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "515e3fe76290fd954abfcf26b445107b13b17995d2bf9164fe06c77338fe3d9a"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mqtt2ntfy/releases/download/v0.0.1/mqtt2ntfy-0.0.1-darwin-amd64.tar.gz"
      sha256 "a3e05525c60aaead5e971421ef89dd83448442a510533fdf121fd9dc7640e23f"
    end

    on_arm do
      url "https://github.com/cdzombak/mqtt2ntfy/releases/download/v0.0.1/mqtt2ntfy-0.0.1-darwin-arm64.tar.gz"
      sha256 "a5e14a85d075d21a1e3a9f939201667948512c14ab7707dff5a9ab96d3f41b80"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/mqtt2ntfy/releases/download/v0.0.1/mqtt2ntfy-0.0.1-linux-amd64.tar.gz"
      sha256 "64cadba9c81aad2ab291f25db819532f8b2cf01254ccd75a7bdc58cd19d3ed1b"
    end

    on_arm do
      url "https://github.com/cdzombak/mqtt2ntfy/releases/download/v0.0.1/mqtt2ntfy-0.0.1-linux-arm64.tar.gz"
      sha256 "d10afb563c03eb9603a682975d367a67ce4fbc4955f061c3cb88c3b744d73373"
    end
  end

  def install
    bin.install "mqtt2ntfy"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/mqtt2ntfy -version"))
  end
end
