# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mqtt2influxdb < Formula
  desc "Opinionated and intentionally scope-limited mqtt to influxdb bridge"
  homepage "https://github.com/cdzombak/mqtt2influxdb"
  url "https://github.com/cdzombak/mqtt2influxdb/archive/refs/tags/v0.0.9.tar.gz"
  version "0.0.9"
  sha256 "820baeb776b7f607a29ff1fb226198c62321f296c20ad878515d7d832a567b32"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v0.0.9/mqtt2influxdb-0.0.9-darwin-amd64.tar.gz"
      sha256 "02801b30c1fdd1bfae0501bb52db94aa56a9c289d6c00968348c94136cae908c"
    end

    on_arm do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v0.0.9/mqtt2influxdb-0.0.9-darwin-arm64.tar.gz"
      sha256 "1ce4dac966e2fa5b986469d0e386f035474d36a3808fe39434947151c5782874"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v0.0.9/mqtt2influxdb-0.0.9-linux-amd64.tar.gz"
      sha256 "2aa081973dcb556c04424758314f146630a5c45f8ccdf15ca27d68ba4a322b4d"
    end

    on_arm do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v0.0.9/mqtt2influxdb-0.0.9-linux-arm64.tar.gz"
      sha256 "40b1d3addaa5702898255e63a974bc1047f344640a767bfaf174552df039bc23"
    end
  end

  def install
    bin.install "mqtt2influxdb"
  end

  test do
    assert_match("0.0.9", shell_output("#{bin}/mqtt2influxdb -version"))
  end
end
