# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mqtt2influxdb < Formula
  desc "Opinionated and intentionally scope-limited mqtt to influxdb bridge"
  homepage "https://github.com/cdzombak/mqtt2influxdb"
  url "https://github.com/cdzombak/mqtt2influxdb/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "c0d5869bc33db93180486c828d47aca38e2b504e1f2e58236190915ea7c9d2da"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v1.0.0/mqtt2influxdb-1.0.0-darwin-amd64.tar.gz"
      sha256 "f7041cb62e432fd1495b084c63e1111c7ae46593f6b2caa7f2cb6040cb38137e"
    end

    on_arm do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v1.0.0/mqtt2influxdb-1.0.0-darwin-arm64.tar.gz"
      sha256 "9f59bae29f9b4eed257d128171fc077089006d774fcc63d94229b854b941f12a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v1.0.0/mqtt2influxdb-1.0.0-linux-amd64.tar.gz"
      sha256 "bf6dfd659cb38b38161b9800a436e6306dfc44bb67b876626537b142ceebf910"
    end

    on_arm do
      url "https://github.com/cdzombak/mqtt2influxdb/releases/download/v1.0.0/mqtt2influxdb-1.0.0-linux-arm64.tar.gz"
      sha256 "abffce65e39a9306823c7ce64955bdfe17e0ba4fcd804e128f0155b28fce848e"
    end
  end

  def install
    bin.install "mqtt2influxdb"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/mqtt2influxdb -version"))
  end
end
