# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Msync < Formula
  desc "Maintain a lower-bitrate copy of a music library in sync with the main copy"
  homepage "https://github.com/cdzombak/msync"
  url "https://github.com/cdzombak/msync/archive/refs/tags/v0.7.0.tar.gz"
  version "0.7.0"
  sha256 "adb6b7c1553be564cbb0cf91d7be869893d500e33f02d645e7285599969f9d5d"
  license "LGPL-2.1"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/msync/releases/download/v0.7.0/msync-0.7.0-darwin-amd64.tar.gz"
      sha256 "424c298504200db711baba78f2fcdacde3ed23eac409456c7e50163e948e0b04"
    end

    on_arm do
      url "https://github.com/cdzombak/msync/releases/download/v0.7.0/msync-0.7.0-darwin-arm64.tar.gz"
      sha256 "2108e9b2bfd511e4957de2bd6585222ea1eba9f118d381ea410dea0baf3931c4"
    end
  end

  def install
    bin.install "msync"
  end

  test do
    assert_match("0.7.0", shell_output("#{bin}/msync -version"))
  end
end
