# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class NutInfluxConnector < Formula
  desc "Ship energy usage data and other ups stats from network-ups-tools to influxdb"
  homepage "https://github.com/cdzombak/nut_influx_connector"
  url "https://github.com/cdzombak/nut_influx_connector/archive/refs/tags/v1.1.1.tar.gz"
  version "1.1.1"
  sha256 "8d45d896bf6332bd9e3872bd20590f857f09f0173a44897d18d0a0d1823ae25a"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.1.1/nut_influx_connector-1.1.1-darwin-amd64.tar.gz"
      sha256 "1ee337c72c3a53564d2e5be3ba79b3664258ac0662c87dc99344c342f6b9548b"
    end

    on_arm do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.1.1/nut_influx_connector-1.1.1-darwin-arm64.tar.gz"
      sha256 "2e6d07c2adf387df80dd8493a2c9cdc1e21d081c3d1e83dbc002b2deb4c15820"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.1.1/nut_influx_connector-1.1.1-linux-amd64.tar.gz"
      sha256 "62ef9fb50bb16e032397b4d69754a26920a65e429773b6b6b0b6f817d2b1a81f"
    end

    on_arm do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.1.1/nut_influx_connector-1.1.1-linux-arm64.tar.gz"
      sha256 "49b7a4e1a14608fb8efb15a229a6a46a524a2a5dad1cdd6de98d3d1545d09c85"
    end
  end

  def install
    bin.install "nut_influx_connector"
  end

  test do
    assert_match("1.1.1", shell_output("#{bin}/nut_influx_connector -version"))
  end
end
