# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class NutInfluxConnector < Formula
  desc "Ship energy usage data &amp; ups stats from network-ups-tools to influxdb/mqtt"
  homepage "https://github.com/cdzombak/nut_influx_connector"
  url "https://github.com/cdzombak/nut_influx_connector/archive/refs/tags/v1.2.0.tar.gz"
  version "1.2.0"
  sha256 "bc37814512b0e397d1f67b3fbd5c294e960c77e9b382912d2078dd8e28925838"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.2.0/nut_influx_connector-1.2.0-darwin-amd64.tar.gz"
      sha256 "b83bc75b62757a3fe76d17aa060afb1209c6264330dfb82597cd436401e06bab"
    end

    on_arm do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.2.0/nut_influx_connector-1.2.0-darwin-arm64.tar.gz"
      sha256 "adb2879ed6e776d2b75ff09673c8aee5867cf4784f4848b886c148440baace80"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.2.0/nut_influx_connector-1.2.0-linux-amd64.tar.gz"
      sha256 "5bb852ee62a32fe8444698dceb65ab081b8aea52a7491bfa041edc0a2ed94609"
    end

    on_arm do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.2.0/nut_influx_connector-1.2.0-linux-arm64.tar.gz"
      sha256 "3b2faae343c939effcab387732ecdecd01bef01b720205c66425d987166c719c"
    end
  end

  def install
    bin.install "nut_influx_connector"
  end

  test do
    assert_match("1.2.0", shell_output("#{bin}/nut_influx_connector -version"))
  end
end
