# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class NutInfluxConnector < Formula
  desc "Ship energy usage data &amp; ups stats from network-ups-tools to influxdb/mqtt"
  homepage "https://github.com/cdzombak/nut_influx_connector"
  url "https://github.com/cdzombak/nut_influx_connector/archive/refs/tags/v1.2.1.tar.gz"
  version "1.2.1"
  sha256 "7e7856883c1f8599633abe83eae74ce70cc6baa3e94ee581b164e5fe0440dfaf"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.2.1/nut_influx_connector-1.2.1-darwin-amd64.tar.gz"
      sha256 "897e23856ed4c4811b50ca49459114787accad2bec957b7826254672981f0036"
    end

    on_arm do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.2.1/nut_influx_connector-1.2.1-darwin-arm64.tar.gz"
      sha256 "939194d10ba02b133b52a2de559c5922e4eaac7243295441a1e626ee55c50aa6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.2.1/nut_influx_connector-1.2.1-linux-amd64.tar.gz"
      sha256 "8457670fc93fa652a2d1c34fb3b69b8556c9bc86366e232818a9f6f588a3da0a"
    end

    on_arm do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.2.1/nut_influx_connector-1.2.1-linux-arm64.tar.gz"
      sha256 "ac99e0050b1802b9ae86b9f0dd1d8daf0c49ecc4fc9e0656c33ea00f5b4b2aa0"
    end
  end

  def install
    bin.install "nut_influx_connector"
  end

  test do
    assert_match("1.2.1", shell_output("#{bin}/nut_influx_connector -version"))
  end
end
