# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class NutInfluxConnector < Formula
  desc "Ship energy usage data and other ups stats from network-ups-tools to influxdb"
  homepage "https://github.com/cdzombak/nut_influx_connector"
  url "https://github.com/cdzombak/nut_influx_connector/archive/refs/tags/v1.1.2.tar.gz"
  version "1.1.2"
  sha256 "a70353c0f265cf00201bba9420fc3f57edca3257d9f2d8574b5111b7891c5d04"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.1.2/nut_influx_connector-1.1.2-darwin-amd64.tar.gz"
      sha256 "1a046d05e4f4be7435e6b5178f78f88e290d015bd40e05aea75c8cd506297d37"
    end

    on_arm do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.1.2/nut_influx_connector-1.1.2-darwin-arm64.tar.gz"
      sha256 "1dfb4f62b5289dae6149727f55a8d11c7555330f95791f234ddb8e4c6360cd1b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.1.2/nut_influx_connector-1.1.2-linux-amd64.tar.gz"
      sha256 "385bbc15ed8ba574c9ef73ca75e7ba3aa7d86c2bc7b6ea5016dc68a155c192cb"
    end

    on_arm do
      url "https://github.com/cdzombak/nut_influx_connector/releases/download/v1.1.2/nut_influx_connector-1.1.2-linux-arm64.tar.gz"
      sha256 "424c6d287453ae6a1b06eac436607ae49c2d6c1431321deb328af99cbe5402aa"
    end
  end

  def install
    bin.install "nut_influx_connector"
  end

  test do
    assert_match("1.1.2", shell_output("#{bin}/nut_influx_connector -version"))
  end
end
