# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class OpenweatherInfluxdbConnector < Formula
  desc "Write current weather conditions from openweathermap to influxdb"
  homepage "https://github.com/cdzombak/openweather-influxdb-connector"
  url "https://github.com/cdzombak/openweather-influxdb-connector/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "176c9556e08047e90422b2983e45dbebce6a7657374878d3849c99fa9b3da312"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.0.0/openweather-influxdb-connector-1.0.0-darwin-amd64.tar.gz"
      sha256 "094e37fe7eac10706cc9fe65c2eb872cbbb8a4f1d5f85cefdc2b25e33c7bd20c"
    end

    on_arm do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.0.0/openweather-influxdb-connector-1.0.0-darwin-arm64.tar.gz"
      sha256 "91ac3835c4d238dda1142228f9ae0417a514ca831886a59bdbacd2db6a6ee6ae"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.0.0/openweather-influxdb-connector-1.0.0-linux-amd64.tar.gz"
      sha256 "f761b605d4f875f5a9db04b94d241407841f7f98575efc310d65caf6a037ddd6"
    end

    on_arm do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.0.0/openweather-influxdb-connector-1.0.0-linux-arm64.tar.gz"
      sha256 "47f652ffd8a0667a0197c7304f0e9b9428dc25f11408148b36de9c0463b9fbec"
    end
  end

  def install
    bin.install "openweather-influxdb-connector"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/openweather-influxdb-connector -version"))
  end
end
