# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class OpenweatherInfluxdbConnector < Formula
  desc "Write current weather conditions from openweathermap to influxdb"
  homepage "https://github.com/cdzombak/openweather-influxdb-connector"
  url "https://github.com/cdzombak/openweather-influxdb-connector/archive/refs/tags/v1.4.0.tar.gz"
  version "1.4.0"
  sha256 "eb313d4b03aad6d820b2548935251b489c6c5c8c5f267e616b9202efbc2f6f95"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.4.0/openweather-influxdb-connector-1.4.0-darwin-amd64.tar.gz"
      sha256 "6c273034e8f757e344ace0133296f36e4a805a7d771c6b4482d0e58bab9735c6"
    end

    on_arm do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.4.0/openweather-influxdb-connector-1.4.0-darwin-arm64.tar.gz"
      sha256 "faca8963b2a663d9a799a612fafdd72d318a787b3ebc948a9657722368f9b78b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.4.0/openweather-influxdb-connector-1.4.0-linux-amd64.tar.gz"
      sha256 "6db0a7f8396cef16e677a665ea0c2a223f41795090959b59a816344ddb410f56"
    end

    on_arm do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.4.0/openweather-influxdb-connector-1.4.0-linux-arm64.tar.gz"
      sha256 "f2fd411f8d58f7c4fc2def2285ea2caafe620a32612de0b29daa60178a6373a7"
    end
  end

  def install
    bin.install "openweather-influxdb-connector"
  end

  test do
    assert_match("1.4.0", shell_output("#{bin}/openweather-influxdb-connector -version"))
  end
end
