# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class OpenweatherInfluxdbConnector < Formula
  desc "Write current weather openweathermap conditions to influxdb or mqtt"
  homepage "https://github.com/cdzombak/openweather-influxdb-connector"
  url "https://github.com/cdzombak/openweather-influxdb-connector/archive/refs/tags/v1.5.0.tar.gz"
  version "1.5.0"
  sha256 "207a4b9727e5c1d21b88c2dfc372c2c67c09bcd5f89b839c7067119c9f62fd9a"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.5.0/openweather-influxdb-connector-1.5.0-darwin-amd64.tar.gz"
      sha256 "ae90f289c6ae65ea26df8334da204a989b6e0e577ee9b5733212cd74832ee8e1"
    end

    on_arm do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.5.0/openweather-influxdb-connector-1.5.0-darwin-arm64.tar.gz"
      sha256 "dfe2bfa4acf3914d60c71f49c0ce388f5d80344bbe1e892d560d0251dd61ed51"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.5.0/openweather-influxdb-connector-1.5.0-linux-amd64.tar.gz"
      sha256 "aaea96b587c14cefb9cb9777d3942f87f45f27ac049ba8368e5b98ddb17ac839"
    end

    on_arm do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.5.0/openweather-influxdb-connector-1.5.0-linux-arm64.tar.gz"
      sha256 "3cc0aaef235443325801b61247a240b667454a8e3fcc34f45cdd29426775c44b"
    end
  end

  def install
    bin.install "openweather-influxdb-connector"
  end

  test do
    assert_match("1.5.0", shell_output("#{bin}/openweather-influxdb-connector -version"))
  end
end
