# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class OpenweatherInfluxdbConnector < Formula
  desc "Write current weather conditions from openweathermap to influxdb"
  homepage "https://github.com/cdzombak/openweather-influxdb-connector"
  url "https://github.com/cdzombak/openweather-influxdb-connector/archive/refs/tags/v1.2.1.tar.gz"
  version "1.2.1"
  sha256 "7891563a62f72f7217005d3351e506421604a1eb3b21aede28ca93779e78e383"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.2.1/openweather-influxdb-connector-1.2.1-darwin-amd64.tar.gz"
      sha256 "036c475676752752a4eced4e9ad79ee03ffda07cbcdb1c508ff7a4b95941788c"
    end

    on_arm do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.2.1/openweather-influxdb-connector-1.2.1-darwin-arm64.tar.gz"
      sha256 "eb36dc147e52b34008df0c3120fe56e61d93a98e101c4c72494589a656d5e5bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.2.1/openweather-influxdb-connector-1.2.1-linux-amd64.tar.gz"
      sha256 "0cabd7e722a74a1d50c4341770a212c43ae5eac85c703be4044f461bb4b6b5e5"
    end

    on_arm do
      url "https://github.com/cdzombak/openweather-influxdb-connector/releases/download/v1.2.1/openweather-influxdb-connector-1.2.1-linux-arm64.tar.gz"
      sha256 "ae998c0dca6f0c668b8b1582803167d329d57a51817b0d57a96ddc5f9e3c9964"
    end
  end

  def install
    bin.install "openweather-influxdb-connector"
  end

  test do
    assert_match("1.2.1", shell_output("#{bin}/openweather-influxdb-connector -version"))
  end
end
