# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class PapercastArchiver < Formula
  desc "Tiny web server with a ui for archiving instapaper articles. integrates with cdz"
  homepage "https://github.com/cdzombak/papercast-archiver"
  url "https://github.com/cdzombak/papercast-archiver/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "5391f570f288f1fdbd2c73bf14e7e5dfe610126f911061a1c0e9b655ca53f7e2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/papercast-archiver/releases/download/v0.0.1/papercast-archiver-0.0.1-darwin-amd64.tar.gz"
      sha256 "91de7481b79f5310dd1d0e36e9aeb22bc9c8b491692ac799a52a949044904f9d"
    end

    on_arm do
      url "https://github.com/cdzombak/papercast-archiver/releases/download/v0.0.1/papercast-archiver-0.0.1-darwin-arm64.tar.gz"
      sha256 "8460fd18d378240a22f9d7b0e44a705c15f89eae7760379ae725afc8c786e2a3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/papercast-archiver/releases/download/v0.0.1/papercast-archiver-0.0.1-linux-amd64.tar.gz"
      sha256 "e07ebca05c9f99aaba8418d146351fd3af9fbb1cf09435c3dc198cdf84a26058"
    end

    on_arm do
      url "https://github.com/cdzombak/papercast-archiver/releases/download/v0.0.1/papercast-archiver-0.0.1-linux-arm64.tar.gz"
      sha256 "daed854b03e7b58d700a5dc1830e51a168f0eb2e16a72bbf7869797361ed6645"
    end
  end

  def install
    bin.install "papercast-archiver"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/papercast-archiver -version"))
  end
end
