# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Papercast < Formula
  desc "Generate a personal podcast of your instapaper reading queue"
  homepage "https://github.com/cdzombak/papercast"
  url "https://github.com/cdzombak/papercast/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "eb9618ca9686ec378c8df5b099ac2652f5ad8455311cc2e2fb6d3d3fd0017b25"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/papercast/releases/download/v0.0.1/papercast-0.0.1-darwin-amd64.tar.gz"
      sha256 "0888c9ce43412bc0fc1fe07a12d3df4a050255d199386ecd4a3bff24eafc7a77"
    end

    on_arm do
      url "https://github.com/cdzombak/papercast/releases/download/v0.0.1/papercast-0.0.1-darwin-arm64.tar.gz"
      sha256 "04f1c8f22ffd889e0c3131af5b3af6597c88ffd5de1b7b5b21d3a3b45f0b3fbb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/papercast/releases/download/v0.0.1/papercast-0.0.1-linux-amd64.tar.gz"
      sha256 "5fa0885585abccd8f88f1a22f2fc472af4259a119cf52b903b21fe36b159dee9"
    end

    on_arm do
      url "https://github.com/cdzombak/papercast/releases/download/v0.0.1/papercast-0.0.1-linux-arm64.tar.gz"
      sha256 "4c2c07ce741c817d99083c2709492c445d3bdf4a1e7b6dd509e953cd26b56f1b"
    end
  end

  def install
    bin.install "papercast"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/papercast -version"))
  end
end
