# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pdate < Formula
  desc "Date/time parsing on the cli"
  homepage "https://github.com/cdzombak/pdate"
  url "https://github.com/cdzombak/pdate/archive/refs/tags/v1.1.1.tar.gz"
  version "1.1.1"
  sha256 "89523bd5292dba7b0bd7db241d4315c5e7f37cb4e831c19de0bbd1be613f5da7"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/pdate/releases/download/v1.1.1/pdate-1.1.1-darwin-amd64.tar.gz"
      sha256 "6ffe867c3498c317528e39b8ebdc59f847bc95f9c8cddfc0b7a745fe5be047f0"
    end

    on_arm do
      url "https://github.com/cdzombak/pdate/releases/download/v1.1.1/pdate-1.1.1-darwin-arm64.tar.gz"
      sha256 "c784a9c1f3e670cb301036a59e233945334723012a65a982effbcbe4e8c9213f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/pdate/releases/download/v1.1.1/pdate-1.1.1-linux-amd64.tar.gz"
      sha256 "edc37eb037dc0873e4ac2ad440f09958e531f1617cb985a04b60c6bc6e2f4c2a"
    end

    on_arm do
      url "https://github.com/cdzombak/pdate/releases/download/v1.1.1/pdate-1.1.1-linux-arm64.tar.gz"
      sha256 "c9416c5c09196807bc698353e56c34312db0f4fb0169635bb771fba99a6361b6"
    end
  end

  def install
    bin.install "pdate"
  end

  test do
    assert_match("1.1.1", shell_output("#{bin}/pdate -version"))
  end
end
