# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pdate < Formula
  desc "Date/time parsing on the cli"
  homepage "https://github.com/cdzombak/pdate"
  url "https://github.com/cdzombak/pdate/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "3cbc9e48a43563f1226b910dde4bdf59226b80dfe63f3c713b0a70bf49ee505b"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/pdate/releases/download/v1.0.1/pdate-1.0.1-darwin-amd64.tar.gz"
      sha256 "18a4b5f7a24df059fd72b5bc2906fb7634c7632191ae2a1ac62f6d45bb46bdae"
    end

    on_arm do
      url "https://github.com/cdzombak/pdate/releases/download/v1.0.1/pdate-1.0.1-darwin-arm64.tar.gz"
      sha256 "4b03594f51a1b7279cbb5c90d33c3db8e388e2c2622f30a5578876b537255f18"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/pdate/releases/download/v1.0.1/pdate-1.0.1-linux-amd64.tar.gz"
      sha256 "661fe220d3972199889947c36e57ecba82e0e33971f40cfd6b2529b1554fe258"
    end

    on_arm do
      url "https://github.com/cdzombak/pdate/releases/download/v1.0.1/pdate-1.0.1-linux-arm64.tar.gz"
      sha256 "5a63e2adf21ab3576922c17993bdf839d8e1e8975d8b10d26db39ec626268a6b"
    end
  end

  def install
    bin.install "pdate"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/pdate -version"))
  end
end
