# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Purpleair2mqtt < Formula
  desc "Pull sensor data from your local purpleair sensors - no cloud needed"
  homepage "https://github.com/cdzombak/purpleair2mqtt"
  url "https://github.com/cdzombak/purpleair2mqtt/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "a74e8c262994638305ce07f3dbff72297e946a70d60dd65b22cdffefaf304ff2"
  license "NOASSERTION"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/purpleair2mqtt/releases/download/v1.0.0/purpleair2mqtt-1.0.0-darwin-amd64.tar.gz"
      sha256 "c91636beea13cc22b2f140267c397ed1959ce910ae23cce76340555df9279aaa"
    end

    on_arm do
      url "https://github.com/cdzombak/purpleair2mqtt/releases/download/v1.0.0/purpleair2mqtt-1.0.0-darwin-arm64.tar.gz"
      sha256 "807f4121c36b6b505a49ca5ef65fd937bbd5379e1e6953e5373ad6accb11ad49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/purpleair2mqtt/releases/download/v1.0.0/purpleair2mqtt-1.0.0-linux-amd64.tar.gz"
      sha256 "922d218123b0a711640a127b7de7b97dffa412b0667d7d16227b5a0b25247bdc"
    end

    on_arm do
      url "https://github.com/cdzombak/purpleair2mqtt/releases/download/v1.0.0/purpleair2mqtt-1.0.0-linux-arm64.tar.gz"
      sha256 "0dc0b6aeff7ad841c16d526edcb0904f4b67918b97696f470a092aa684ac5610"
    end
  end

  def install
    bin.install "purpleair2mqtt"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/purpleair2mqtt -version"))
  end
end
