# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Purpleair2mqtt < Formula
  desc "Pull sensor data from your local purpleair sensors - no cloud needed"
  homepage "https://github.com/cdzombak/purpleair2mqtt"
  url "https://github.com/cdzombak/purpleair2mqtt/archive/refs/tags/v1.1.1.tar.gz"
  version "1.1.1"
  sha256 "6098188bfa8e5f96cf63afeab0f57ea2b1990083eec2123baf045f61adb94fc5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/purpleair2mqtt/releases/download/v1.1.1/purpleair2mqtt-1.1.1-darwin-amd64.tar.gz"
      sha256 "b42bd69c59d6373743c6a5ec9f6dadd901f25f13bfd47e5664e664f6fd0f2244"
    end

    on_arm do
      url "https://github.com/cdzombak/purpleair2mqtt/releases/download/v1.1.1/purpleair2mqtt-1.1.1-darwin-arm64.tar.gz"
      sha256 "c9f35138a1b99f953b5bbbcee8782ff14bd24f6dd257ab8ba4b34d2c5191b549"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/purpleair2mqtt/releases/download/v1.1.1/purpleair2mqtt-1.1.1-linux-amd64.tar.gz"
      sha256 "4ce0105b4ac0c9eedd8a235fbc81ef6c3fb7f34b5f11109e137703c4edc78e5f"
    end

    on_arm do
      url "https://github.com/cdzombak/purpleair2mqtt/releases/download/v1.1.1/purpleair2mqtt-1.1.1-linux-arm64.tar.gz"
      sha256 "40698d604c0ce94ed2736f63bd9b78fc766d4bc54734a69575816b1d31a2deb1"
    end
  end

  def install
    bin.install "purpleair2mqtt"
  end

  test do
    assert_match("1.1.1", shell_output("#{bin}/purpleair2mqtt -version"))
  end
end
