# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class RaindropPublicRssFeed < Formula
  desc "Generate a public rss, atom, or json feed from your raindrop.io bookmarks tagged"
  homepage "https://github.com/cdzombak/raindrop-public-rss-feed"
  url "https://github.com/cdzombak/raindrop-public-rss-feed/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "b8a0957453f0ae81161914571c88d4c01d8176e7217af0b40d359a4530470990"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/raindrop-public-rss-feed/releases/download/v0.0.1/raindrop-public-rss-feed-0.0.1-darwin-amd64.tar.gz"
      sha256 "d51de73a4dce8d65a3bd9065f68204dd5691b8579360259758dd59aa42118c02"
    end

    on_arm do
      url "https://github.com/cdzombak/raindrop-public-rss-feed/releases/download/v0.0.1/raindrop-public-rss-feed-0.0.1-darwin-arm64.tar.gz"
      sha256 "7569ce1e9e47ef3d3dc58dff423b9316d13fee4acf371ed33c7293301a08a832"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/raindrop-public-rss-feed/releases/download/v0.0.1/raindrop-public-rss-feed-0.0.1-linux-amd64.tar.gz"
      sha256 "f7a66f9b58c160c61e12a7c869b38c2d6e658d038c2bee71f3bda2d128f14ad7"
    end

    on_arm do
      url "https://github.com/cdzombak/raindrop-public-rss-feed/releases/download/v0.0.1/raindrop-public-rss-feed-0.0.1-linux-arm64.tar.gz"
      sha256 "a88ae36424ff4aa082ee9e329c3f4b76daa06eaf124d20b3dd655d37a426c658"
    end
  end

  def install
    bin.install "raindrop-public-rss-feed"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/raindrop-public-rss-feed -version"))
  end
end
