# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Runner < Formula
  desc "Lightweight wrapper for better cron jobs and containers"
  homepage "https://github.com/cdzombak/runner"
  url "https://github.com/cdzombak/runner/archive/refs/tags/v2.11.0.tar.gz"
  version "2.11.0"
  sha256 "a5b9500e56e62a28a45f278fa7171399ae6836c1b3119cd20258a800e78a3028"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/runner/releases/download/v2.11.0/runner-2.11.0-darwin-amd64.tar.gz"
      sha256 "405b7f425c7db3d855b5127a2e67113efe0d249b93bf20d0dce361fa8f55bac2"
    end

    on_arm do
      url "https://github.com/cdzombak/runner/releases/download/v2.11.0/runner-2.11.0-darwin-arm64.tar.gz"
      sha256 "8ae3e5c1b336fc678e884380c87cf3f9030eaeb52ef33f0c0662a66dc7573001"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/runner/releases/download/v2.11.0/runner-2.11.0-linux-amd64.tar.gz"
      sha256 "2acf602f42e7506a140d18a3e19aa84cafa482cae3fe0081e7e966097ab24cd0"
    end

    on_arm do
      url "https://github.com/cdzombak/runner/releases/download/v2.11.0/runner-2.11.0-linux-arm64.tar.gz"
      sha256 "f1fed2d0dbd92a57f767607e764e792a04351e355bf47a2eb41814bbb0272061"
    end
  end

  def install
    bin.install "runner"
  end

  test do
    assert_match("2.11.0", shell_output("#{bin}/runner -version"))
  end
end
