# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Runner < Formula
  desc "Lightweight wrapper for better cron jobs and containers"
  homepage "https://github.com/cdzombak/runner"
  url "https://github.com/cdzombak/runner/archive/refs/tags/v2.9.2.tar.gz"
  version "2.9.2"
  sha256 "6b47d3d5271aeffc4c28aa1e2f4bcb751c5e14a79a81b2e5be1bf2c40025d378"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/runner/releases/download/v2.9.2/runner-2.9.2-darwin-amd64.tar.gz"
      sha256 "208a24b9221540fedd84723e7c2feef8c36ca8eacdcbe5fd4e387a1c75e26aea"
    end

    on_arm do
      url "https://github.com/cdzombak/runner/releases/download/v2.9.2/runner-2.9.2-darwin-arm64.tar.gz"
      sha256 "782926f02aca67187d8d45d267936b2f21fd39f362d7f440faf2823d31ca3efa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/runner/releases/download/v2.9.2/runner-2.9.2-linux-amd64.tar.gz"
      sha256 "289878d3508a7fa6b25cd746f457366b80c11e2a19bc4bc177ae9029187cfdfa"
    end

    on_arm do
      url "https://github.com/cdzombak/runner/releases/download/v2.9.2/runner-2.9.2-linux-arm64.tar.gz"
      sha256 "163ffdb259b67220fe49db01af76303c47627de699076fbfe708e38c78fa3cf9"
    end
  end

  def install
    bin.install "runner"
  end

  test do
    assert_match("2.9.2", shell_output("#{bin}/runner -version"))
  end
end
