# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Runner < Formula
  desc "Lightweight wrapper for better cron jobs and containers"
  homepage "https://github.com/cdzombak/runner"
  url "https://github.com/cdzombak/runner/archive/refs/tags/v2.8.4.tar.gz"
  sha256 "3b016ed3af0f54d5f95f6925264723069b64054be5378d82bdbcc73bf19b910b"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/runner/releases/download/v2.8.4/runner-2.8.4-darwin-amd64.tar.gz"
      sha256 "f3c69ae2919993e92361701720ac0408baec31c6e63b77624a43baef21ad130c"
    end

    on_arm do
      url "https://github.com/cdzombak/runner/releases/download/v2.8.4/runner-2.8.4-darwin-arm64.tar.gz"
      sha256 "2f6e14502e149f91a8ec96f77fae13c742a6916c1fe5fd0d240dd39e9b12b206"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/runner/releases/download/v2.8.4/runner-2.8.4-linux-amd64.tar.gz"
      sha256 "4bed02d1d2f103d76c2c2471384bde6a2590a42b3271d1f875e605410f5f7b9b"
    end

    on_arm do
      url "https://github.com/cdzombak/runner/releases/download/v2.8.4/runner-2.8.4-linux-arm64.tar.gz"
      sha256 "77f1868b6a8c08bfe246245dfacbe5b7545212f0ce04232a8e83cd8f9ba0e531"
    end
  end

  def install
    bin.install "runner"
  end

  test do
    assert_match("2.8.4", shell_output("#{bin}/runner -version"))
  end
end
