# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Runner < Formula
  desc "Lightweight wrapper for better cron jobs and containers"
  homepage "https://github.com/cdzombak/runner"
  url "https://github.com/cdzombak/runner/archive/refs/tags/v2.8.2.tar.gz"
  sha256 "feff4274fc373f561899ee8221a438db63f1a6c43e000b2170677ca4b09e1de4"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/runner/releases/download/v2.8.2/runner-2.8.2-darwin-amd64.tar.gz"
      sha256 "87fc4526ffb46726fd34b8910a66b68f97fe1c7d02b7d332ce037a2c7a1a5074"
    end

    on_arm do
      url "https://github.com/cdzombak/runner/releases/download/v2.8.2/runner-2.8.2-darwin-arm64.tar.gz"
      sha256 "517b0d5028942e6028c84cad7824355a94826374ae612a200a0a763137838aad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/runner/releases/download/v2.8.2/runner-2.8.2-linux-amd64.tar.gz"
      sha256 "015908d291614f9f1a279efc41e630752b69f941ed7f99e00fa7800b596fd9c1"
    end

    on_arm do
      url "https://github.com/cdzombak/runner/releases/download/v2.8.2/runner-2.8.2-linux-arm64.tar.gz"
      sha256 "32034118caddf12d2d2b364f2fccabf52043049310d69160212f1b9ca5dfd03e"
    end
  end

  def install
    bin.install "runner"
  end

  test do
    assert_match("2.8.2", shell_output("#{bin}/runner -version"))
  end
end
