# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Trailcamai < Formula
  desc "Ai-powered trail camera image and video organizer"
  homepage "https://github.com/cdzombak/trailcamai"
  url "https://github.com/cdzombak/trailcamai/archive/refs/tags/v0.0.2.tar.gz"
  version "0.0.2"
  sha256 "0c88faef530e18869c174f97915d32de32697ac5b49cd6f6b9cdd1f00b8d2862"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/trailcamai/releases/download/v0.0.2/trailcamai-0.0.2-darwin-amd64.tar.gz"
      sha256 "2f45c8f64099eed6627cc71c513584deddabba8260ce1f7fe2b9f991f5cb157a"
    end

    on_arm do
      url "https://github.com/cdzombak/trailcamai/releases/download/v0.0.2/trailcamai-0.0.2-darwin-arm64.tar.gz"
      sha256 "73ef143da39bde4ea7d70a1190296b01cb8e41cc35afd59b59a089693ca53296"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/trailcamai/releases/download/v0.0.2/trailcamai-0.0.2-linux-amd64.tar.gz"
      sha256 "84766901289b8b33df58ab6f5a7297ca1ec3076737ce506e2b1adb1ca981ac4d"
    end

    on_arm do
      url "https://github.com/cdzombak/trailcamai/releases/download/v0.0.2/trailcamai-0.0.2-linux-arm64.tar.gz"
      sha256 "857b84c91a23323e6e683575415efe82cb924e12d3d0c3c2d2eb229e812f3eb2"
    end
  end

  def install
    bin.install "trailcamai"
  end

  test do
    assert_match("0.0.2", shell_output("#{bin}/trailcamai -version"))
  end
end
