# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Trailcamai < Formula
  desc "Ai-powered trail camera image and video organizer"
  homepage "https://github.com/cdzombak/trailcamai"
  url "https://github.com/cdzombak/trailcamai/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "b9a9ad5b5e909bbaeb0e9b1a2a62221c568b6507a380c50509e538897e1d827e"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/trailcamai/releases/download/v1.0.0/trailcamai-1.0.0-darwin-amd64.tar.gz"
      sha256 "188254264c759ae03bed8e15fd972fddaa58ae3772a67bd57870c60895e32255"
    end

    on_arm do
      url "https://github.com/cdzombak/trailcamai/releases/download/v1.0.0/trailcamai-1.0.0-darwin-arm64.tar.gz"
      sha256 "84b4a28a5294ff2c6e73d08c837b3a0c7a61464edfa29d801752036da288768b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/trailcamai/releases/download/v1.0.0/trailcamai-1.0.0-linux-amd64.tar.gz"
      sha256 "91037373eb97b8cc4f1571a3ba106c5f46741d3f55c3a5e5df149a715fa767bb"
    end

    on_arm do
      url "https://github.com/cdzombak/trailcamai/releases/download/v1.0.0/trailcamai-1.0.0-linux-arm64.tar.gz"
      sha256 "0d97edb345369ed8ddb7ccad4ef76853e440530349d6e7d4ea987c7242a86145"
    end
  end

  def install
    bin.install "trailcamai"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/trailcamai -version"))
  end
end
