# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Unshorten < Formula
  desc "Simple, verbose url unshortener"
  homepage "https://github.com/cdzombak/unshorten"
  url "https://github.com/cdzombak/unshorten/archive/v1.0.0.tar.gz"
  sha256 "2c2e42b5fbc9a86fc65a4ad6aba5897009c8c7ac698c76d651280373df600a60"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/unshorten/releases/download/v1.0.0/unshorten-1.0.0-darwin-amd64.tar.gz"
      sha256 "5dc3c0130c7ed4c8079dffffb8dc89aa3a3ebdb396bfc6d021f400ecf64d1508"
    end

    on_arm do
      url "https://github.com/cdzombak/unshorten/releases/download/v1.0.0/unshorten-1.0.0-darwin-arm64.tar.gz"
      sha256 "79fe04bc5d5b85e1f1e637b29ef0f0284abaad99da57dfeeb4990f8c2bd1a64a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/unshorten/releases/download/v1.0.0/unshorten-1.0.0-linux-amd64.tar.gz"
      sha256 "a29ce3c7e3062ab18285fb585458a3d3034383c2591ed4523b242c62961a6ff2"
    end

    on_arm do
      url "https://github.com/cdzombak/unshorten/releases/download/v1.0.0/unshorten-1.0.0-linux-arm64.tar.gz"
      sha256 "b4b392ad54892f5959ffc15d34f66481685cf0930d8cc672afdfa49d8b74fe20"
    end
  end

  def install
    bin.install "unshorten"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/unshorten -version"))
  end
end
