# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Washmon < Formula
  desc "Figures out when your laundry is done and reminds you periodically until"
  homepage "https://github.com/cdzombak/washmon"
  url "https://github.com/cdzombak/washmon/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "06a926de0f868eced658b045d856930084fe6069d27bbb6d10763e43c393759d"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/washmon/releases/download/v1.0.0/washmon-1.0.0-darwin-amd64.tar.gz"
      sha256 "b430d9527ba14e7c3806e1955f07c74ece6df0cabe4a75a3d4d060ceb3660a38"
    end

    on_arm do
      url "https://github.com/cdzombak/washmon/releases/download/v1.0.0/washmon-1.0.0-darwin-arm64.tar.gz"
      sha256 "b65e7d74370e1f3a2ec8127eb3da0b6cf9c172eb25a2ab22137dbedc9a5dc5e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/washmon/releases/download/v1.0.0/washmon-1.0.0-linux-amd64.tar.gz"
      sha256 "dd708fdbd0740e0a5a66e2ffaa96bc1b3b5e6b5b8c10cbe084a55da8f8bc4786"
    end

    on_arm do
      url "https://github.com/cdzombak/washmon/releases/download/v1.0.0/washmon-1.0.0-linux-arm64.tar.gz"
      sha256 "971e85c1f0a5b597005f833d3e1169e56b563ce64c0d5199f547267e85894a67"
    end
  end

  def install
    bin.install "washmon"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/washmon -version"))
  end
end
