# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Washmon < Formula
  desc "Figures out when a load of laundry is done and reminds you about it peri"
  homepage "https://github.com/cdzombak/washmon"
  url "https://github.com/cdzombak/washmon/archive/refs/tags/v0.0.1.tar.gz"
  version "0.0.1"
  sha256 "9f06e195a68946ce3d9b17b988d92c691ff75aa147f4f4e12506c2bf1f1e7a78"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/washmon/releases/download/v0.0.1/washmon-0.0.1-darwin-amd64.tar.gz"
      sha256 "5d4e8543023fb887b42092117dfcc91d9c952c33c8e4db7484ba8d9712c688af"
    end

    on_arm do
      url "https://github.com/cdzombak/washmon/releases/download/v0.0.1/washmon-0.0.1-darwin-arm64.tar.gz"
      sha256 "3429de1be553b4954fbba426ac7136242008f257611125284c2d70d1fc113575"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/washmon/releases/download/v0.0.1/washmon-0.0.1-linux-amd64.tar.gz"
      sha256 "c67a19acd8a11c1836c32df0b886dfec1b4e8bc26a2ae01dc2e38823e14b0db9"
    end

    on_arm do
      url "https://github.com/cdzombak/washmon/releases/download/v0.0.1/washmon-0.0.1-linux-arm64.tar.gz"
      sha256 "5d0d5bd77f4cb6f4788f55e915e9ba553ff7d42242ee176edea9817ef4f9a110"
    end
  end

  def install
    bin.install "washmon"
  end

  test do
    assert_match("0.0.1", shell_output("#{bin}/washmon -version"))
  end
end
