# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Wdproc < Formula
  desc "Add files synced from writerdeck to day one or things"
  homepage "https://github.com/cdzombak/wdproc"
  url "https://github.com/cdzombak/wdproc/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "6e2246e2fbb56f09d4ddce7b87bf9d2d7e23e21c518fed553f8ee52a93943a83"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/wdproc/releases/download/v1.0.1/wdproc-1.0.1-darwin-amd64.tar.gz"
      sha256 "3f9850bfd0f7b877d7142acbbf2b3546874d1b1d3cb18b4916687a143f720adb"
    end

    on_arm do
      url "https://github.com/cdzombak/wdproc/releases/download/v1.0.1/wdproc-1.0.1-darwin-arm64.tar.gz"
      sha256 "f308ad3a9d6592be0dcdc8067e16ee5c6e065976568513c4e08d40df125e977e"
    end
  end

  def install
    bin.install "wdproc"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/wdproc version"))
  end
end
