# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Wdproc < Formula
  desc "Add files synced from writerdeck to day one or things"
  homepage "https://github.com/cdzombak/wdproc"
  url "https://github.com/cdzombak/wdproc/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "b536e56ba74ef5cac6f71f0c634b2466e9bcbe1e35ec23553a9c0b221c374741"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cdzombak/wdproc/releases/download/v1.0.0/wdproc-1.0.0-darwin-arm64.tar.gz"
      sha256 "13a3f451a87cee18f4d36609d9040c783ec7656a6727053a3c16dbc41a7d6feb"
    end
  end

  on_linux do
  end

  def install
    bin.install "wdproc"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/wdproc version"))
  end
end
