# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Windowstack2 < Formula
  desc "“wait, what was i doing?”"
  homepage "https://github.com/cdzombak/windowstack2"
  url "https://github.com/cdzombak/windowstack2/archive/v1.6.0.tar.gz"
  sha256 "685e0429c0fe712b00d3d6b4216b332079f90edeb97025625445aa9e45f14781"
  license "MIT"

  def install
    bin.install "windowstack2"
  end

  test do
    assert_match("1.6.0", shell_output("#{bin}/windowstack2 -version"))
  end
end
