# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class WxStaAggInflux < Formula
  desc "Aggregator for wind and rain data stored in influxdb"
  homepage "https://github.com/cdzombak/wx-sta-agg-influx"
  url "https://github.com/cdzombak/wx-sta-agg-influx/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "4e22deedff7fb061b70cf8ad7222e8291c32e23d58b43785b412f11b9aaec225"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.1/wx-sta-agg-influx-1.0.1-darwin-amd64.tar.gz"
      sha256 "3b8f2f2a90479488854bd4be375a7f5a1cc48b1c7149627069b6da1644786566"
    end

    on_arm do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.1/wx-sta-agg-influx-1.0.1-darwin-arm64.tar.gz"
      sha256 "611d08d1b0c35c40cd168b70a3492998691474b2d8ed401ad036be82383263e3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.1/wx-sta-agg-influx-1.0.1-linux-amd64.tar.gz"
      sha256 "f08820903512a2a03c899cbfcafca843634ee5f0c812723c59405681f6993b91"
    end

    on_arm do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.1/wx-sta-agg-influx-1.0.1-linux-arm64.tar.gz"
      sha256 "75624af2f027749dea741146339793983e4caafd796a0c97dbc94450006a1598"
    end
  end

  def install
    bin.install "wx-sta-agg-influx"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/wx-sta-agg-influx -version"))
  end
end
