# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class WxStaAggInflux < Formula
  desc "Aggregator for wind and rain data stored in influxdb"
  homepage "https://github.com/cdzombak/wx-sta-agg-influx"
  url "https://github.com/cdzombak/wx-sta-agg-influx/archive/refs/tags/v1.0.3.tar.gz"
  version "1.0.3"
  sha256 "fc7ed95a2438739dcb2f7749695bc702faf08652bcd1a6d38ae2b74b7bda9750"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.3/wx-sta-agg-influx-1.0.3-darwin-amd64.tar.gz"
      sha256 "599e7fd7fe7234594942283d8dcc57dda58fd9a17e17077cbde4ae069cae1b61"
    end

    on_arm do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.3/wx-sta-agg-influx-1.0.3-darwin-arm64.tar.gz"
      sha256 "592d5c09a87199d24f4ae660600699baa8a322ced8b87cfb1a5aeecc6b0ebffa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.3/wx-sta-agg-influx-1.0.3-linux-amd64.tar.gz"
      sha256 "d69e22e09e8912befc5c7b85da006f0204ae671062a5a7e68cec8c97e63c096c"
    end

    on_arm do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.3/wx-sta-agg-influx-1.0.3-linux-arm64.tar.gz"
      sha256 "6b2ede0c9eae5507a58f6a9117eabda282a458b3aae0c2bfd0a0b6789c370656"
    end
  end

  def install
    bin.install "wx-sta-agg-influx"
  end

  test do
    assert_match("1.0.3", shell_output("#{bin}/wx-sta-agg-influx -version"))
  end
end
