# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class WxStaAggInflux < Formula
  desc "Aggregator for wind and rain data stored in influxdb"
  homepage "https://github.com/cdzombak/wx-sta-agg-influx"
  url "https://github.com/cdzombak/wx-sta-agg-influx/archive/refs/tags/v1.0.2.tar.gz"
  version "1.0.2"
  sha256 "2922a42e310dfe225d0ed930b0d8b8acefa7fe91b2c707b69f5b367d7716627f"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.2/wx-sta-agg-influx-1.0.2-darwin-amd64.tar.gz"
      sha256 "aa35a9422ea145867bb4932b3ff5b1da213d1d8f4908de1e9942d49f95f6cf25"
    end

    on_arm do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.2/wx-sta-agg-influx-1.0.2-darwin-arm64.tar.gz"
      sha256 "fbb67defc6e0c7bfc7af65a0ac2a26e77a2163bd6cd5c2242bb0c37bea514834"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.2/wx-sta-agg-influx-1.0.2-linux-amd64.tar.gz"
      sha256 "f1cf00414b27f0b31b7cca2bd7ffe449aad9b90339e0715bf0f02a627ab8d132"
    end

    on_arm do
      url "https://github.com/cdzombak/wx-sta-agg-influx/releases/download/v1.0.2/wx-sta-agg-influx-1.0.2-linux-arm64.tar.gz"
      sha256 "fa1a6f75f097920a29e84d37def052fed06542a09efceb452d5f748769b11b2e"
    end
  end

  def install
    bin.install "wx-sta-agg-influx"
  end

  test do
    assert_match("1.0.2", shell_output("#{bin}/wx-sta-agg-influx -version"))
  end
end
