# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Wxcal < Formula
  desc "Generate an ical feed from the weather.gov forecast api"
  homepage "https://github.com/cdzombak/wxcal"
  url "https://github.com/cdzombak/wxcal/archive/refs/tags/v2.0.0.tar.gz"
  version "2.0.0"
  sha256 "cc7602a46b7f8bea82af1160e0e2713acefd1f04869eb70fe7cc196a55a4a4aa"
  license "LGPL-2.1"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/wxcal/releases/download/v2.0.0/wxcal-2.0.0-darwin-amd64.tar.gz"
      sha256 "287a34cdbb4d363b22a378e1a62ec105cb28019ff3c12f518befd9c6f428a7ce"
    end

    on_arm do
      url "https://github.com/cdzombak/wxcal/releases/download/v2.0.0/wxcal-2.0.0-darwin-arm64.tar.gz"
      sha256 "416ea31bc7ef748f6d9cc6ea6f59ddc3f93b7aa91acb826d445704ee83bc73c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/wxcal/releases/download/v2.0.0/wxcal-2.0.0-linux-amd64.tar.gz"
      sha256 "eda0f90d669cdfa68d346c14f6dc77af8c4e01a7a909d50590cd5df2763465a9"
    end

    on_arm do
      url "https://github.com/cdzombak/wxcal/releases/download/v2.0.0/wxcal-2.0.0-linux-arm64.tar.gz"
      sha256 "0ade7c88f1981eacfc029fd7f2cee70329557d18e4c2cbea567e646ca695738a"
    end
  end

  def install
    bin.install "wxcal"
  end

  test do
    assert_match("2.0.0", shell_output("#{bin}/wxcal -version"))
  end
end
