# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Wxcal < Formula
  desc "Generate an ical feed from the weathergov forecast api"
  homepage "https://github.com/cdzombak/wxcal"
  url "https://github.com/cdzombak/wxcal/archive/refs/tags/v1.1.0.tar.gz"
  sha256 "09e1c1aed448ef4b58a9a28566d255c326b6736743207d2843fac3b4e15c0aca"
  license "LGPL-2.1"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.1.0/wxcal-1.1.0-darwin-amd64.tar.gz"
      sha256 "c450d1a337e56ef48c5ea6864688d91646e42566c029e4c8f2f5c77ae29e9f71"
    end

    on_arm do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.1.0/wxcal-1.1.0-darwin-arm64.tar.gz"
      sha256 "4d279bcb2784b3c331924c42fb8364b2f481649183a2b44459600d8480afa620"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.1.0/wxcal-1.1.0-linux-amd64.tar.gz"
      sha256 "776a8881616270cd5278052645d45d100d6ae8534551cf9fb64c66886a1ba667"
    end

    on_arm do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.1.0/wxcal-1.1.0-linux-arm64.tar.gz"
      sha256 "b0d6274a49c997d6eaa4b25b3d525f9a545c5b4fae803062a53922bfc550d78d"
    end
  end

  def install
    bin.install "wxcal"
  end

  test do
    assert_match("1.1.0", shell_output("#{bin}/wxcal -version"))
  end
end
