# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Wxcal < Formula
  desc "Generate an ical feed from the weathergov forecast api"
  homepage "https://github.com/cdzombak/wxcal"
  url "https://github.com/cdzombak/wxcal/archive/v1.0.1.tar.gz"
  sha256 "6490337c333d65a3380b2cfc35934885727f7f1a266017b850e6059a2b9d2bef"
  license "LGPL-2.1"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.0.1/wxcal-1.0.1-darwin-amd64.tar.gz"
      sha256 "8fffb21f322e2a0dcb5ee7773107287b5ad464b9ddb63e2cabfa77bb061d1570"
    end

    on_arm do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.0.1/wxcal-1.0.1-darwin-arm64.tar.gz"
      sha256 "08ae5ffdf3a7efa9a06a871bd76a536584f95dd6593e2f9cb0de874c86f07854"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.0.1/wxcal-1.0.1-linux-amd64.tar.gz"
      sha256 "08b119417f4fde7ab154c11a584c810b79adc533c6cadfd90d8efa52ac147693"
    end

    on_arm do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.0.1/wxcal-1.0.1-linux-arm64.tar.gz"
      sha256 "9a0d3e1b9a35dfb38163d3042ffe92fbc701f2125cf8945d2c79fd0723ded235"
    end
  end

  def install
    bin.install "wxcal"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/wxcal -version"))
  end
end
