# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Wxcal < Formula
  desc "Generate an ical feed from the weathergov forecast api"
  homepage "https://github.com/cdzombak/wxcal"
  url "https://github.com/cdzombak/wxcal/archive/refs/tags/v1.0.2.tar.gz"
  sha256 "365b02ff9ba9f9443dbd64aad93c5a9d42e78c296322f57363368b91db5f6a2b"
  license "LGPL-2.1"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.0.2/wxcal-1.0.2-darwin-amd64.tar.gz"
      sha256 "cac468ae076ceb5534a99da8cdbe17ae5a3f1314a58e2a83061553e6cf281fe3"
    end

    on_arm do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.0.2/wxcal-1.0.2-darwin-arm64.tar.gz"
      sha256 "652c1e985f311835205620471fa4d69e33a1e89fe5fa4e8e67be115f332ddf7c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.0.2/wxcal-1.0.2-linux-amd64.tar.gz"
      sha256 "1d813c3958f32049b21d0170099dfa26cdab4eca3efa3ca12a5cd045d8715dd3"
    end

    on_arm do
      url "https://github.com/cdzombak/wxcal/releases/download/v1.0.2/wxcal-1.0.2-linux-arm64.tar.gz"
      sha256 "5612fc40dc935718ba47cf3601aba7ce062c9bf9595f86dfa126fc9191a2e0ca"
    end
  end

  def install
    bin.install "wxcal"
  end

  test do
    assert_match("1.0.2", shell_output("#{bin}/wxcal -version"))
  end
end
