# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Xtool < Formula
  desc "Photography workflow helper, mainly focused on exif operations"
  homepage "https://github.com/cdzombak/xtool"
  url "https://github.com/cdzombak/xtool/archive/refs/tags/v1.0.1.tar.gz"
  version "1.0.1"
  sha256 "643d7030aa9964266db82e10ee8727646e0f8ec2514722bd89a08c2c6b735d47"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/xtool/releases/download/v1.0.1/xtool-1.0.1-darwin-amd64.tar.gz"
      sha256 "72e9e895888c0cdeb390f9557778b26f5d4ebc08cdc2c2a3b48e4052b9434afa"
    end

    on_arm do
      url "https://github.com/cdzombak/xtool/releases/download/v1.0.1/xtool-1.0.1-darwin-arm64.tar.gz"
      sha256 "483da75be3e26628fc29bf7ed9d7f1a478107ab90775364e3ca6e4846ab47daa"
    end
  end

  def install
    bin.install "xtool"
  end

  test do
    assert_match("1.0.1", shell_output("#{bin}/xtool version"))
  end
end
