# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Xtool < Formula
  desc "Photography workflow helper, mainly focused on exif operations"
  homepage "https://github.com/cdzombak/xtool"
  url "https://github.com/cdzombak/xtool/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  sha256 "f07babfbf61f3cedfb649174ef58d74805371dab98763d043d2d621587a9cb53"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/cdzombak/xtool/releases/download/v1.0.0/xtool-1.0.0-darwin-amd64.tar.gz"
      sha256 "ea6ab90b400b87a9bc8ff3bc0b1f2d8b72151be0252e3331032480bcd83f934d"
    end

    on_arm do
      url "https://github.com/cdzombak/xtool/releases/download/v1.0.0/xtool-1.0.0-darwin-arm64.tar.gz"
      sha256 "cb56e70606d4eeed081b8a741370e41e1f206a4edd23dc0767e36b17b415f7ba"
    end
  end

  def install
    bin.install "xtool"
  end

  test do
    assert_match("1.0.0", shell_output("#{bin}/xtool version"))
  end
end
